#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate scripts/guides_<lang>.py from translated JSON batches.

The general form of scripts/build_chinese_guides.py, minus the script
conversion that only Chinese needs. Use this for any new language: write one
JSON file per batch under a scratch directory, shaped

    { "<lang>": { "<slug>": {title, h1, description, intro[], steps[][2],
                             sections[][2], faq[][2]} } }

and run this. It is strictly better than appending to a Python module by hand:

  - a batch is valid JSON or it is not, so a broken batch fails loudly;
  - a slug translated twice aborts instead of one copy silently winning;
  - re-running is idempotent, so a batch can be corrected and replayed;
  - progress is reported as n/37 with the missing slugs named, never guessed.

Two guards run over every batch, both from real mistakes:

  STRAY   characters from a script the language does not use. A Cyrillic
          "материал" once reached a Cantonese paragraph and reads as a
          plausible word at a glance — nothing downstream objects to fluent,
          plausible, wrong text.
  DIACRITIC  for languages whose orthography is Latin-plus-diacritics, a
          paragraph with none at all is a strong sign of stripped or
          untranslated copy. Vietnamese without its tone marks is a different
          set of words, not a stylistic variant.

Usage:  python3 scripts/build_lang_guides.py <lang> <batch-dir>
"""
import glob
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Scripts each language must NOT contain. Latin-script languages reject every
# non-Latin block we have shipped copy in; add a row when adding a language.
STRAY = {
    "vi": re.compile("[Ѐ-ӿ֐-ۿ฀-๿"
                     "가-힯぀-ヿ一-鿿]"),
}

# Languages written in Latin script with obligatory diacritics, and the
# fraction of paragraphs that must carry at least one.
DIACRITIC = {
    "vi": re.compile("[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợ"
                     "ùúủũụưừứửữựỳýỷỹỵđ]", re.I),
}

META = {
    "vi": {
        "name": "Vietnamese",
        "upper": "VI",
        "glossary": """Glossary settled on for all 37 guides:

  backup              bản sao lưu
  to merge / merge    hợp nhất
  notes               ghi chú
  highlights          phần tô màu
  bookmarks           dấu trang
  tags                thẻ
  device              thiết bị
  to restore          khôi phục
  Personal Study      Học hỏi cá nhân
  Backup and Restore  Sao lưu và khôi phục
  browser             trình duyệt
  database            cơ sở dữ liệu
  Conflict Reviewer   trình xem lại xung đột
  duplicate           bản trùng lặp
  publication         ấn phẩm
  meeting             buổi nhóm họp
  convention          hội nghị
  talk                bài giảng
  Hebrew Scriptures   phần Kinh Thánh tiếng Hê-bơ-rơ
  Greek Scriptures    phần Kinh Thánh tiếng Hy Lạp""",
    },
}

HEADER = '''# -*- coding: utf-8 -*-
"""%(name)s copy for the static guide pages, keyed by slug.

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["%(code)s"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

%(glossary)s

Generated by scripts/build_lang_guides.py — edit the JSON batches, not this.
"""

GUIDES_%(upper)s = '''


def q(s):
    """A Python string literal that keeps non-ASCII readable in the source."""
    return json.dumps(s, ensure_ascii=False)


def render(guides, order):
    out = ["{\n"]
    for slug in order:
        g = guides[slug]
        out.append("\n %s: {\n" % q(slug))
        for f in ("title", "h1", "description"):
            out.append("  %s: %s,\n" % (q(f), q(g[f])))
        out.append("  \"intro\": [\n")
        for p in g["intro"]:
            out.append("   %s,\n" % q(p))
        out.append("  ],\n")
        for field in ("steps", "sections", "faq"):
            out.append("  \"%s\": [\n" % field)
            for a, b in g[field]:
                out.append("   (%s, %s),\n" % (q(a), q(b)))
            out.append("  ],\n")
        out.append(" },\n")
    out.append("}\n")
    return "".join(out)


def check(lang, slug, g):
    blob = json.dumps(g, ensure_ascii=False)
    stray = STRAY.get(lang)
    if stray:
        m = stray.search(blob)
        if m:
            sys.exit("ABORT %s/%s: stray %r (U+%04X) — wrong script for this "
                     "language" % (lang, slug, m.group(0), ord(m.group(0))))
    dia = DIACRITIC.get(lang)
    if dia:
        # Long prose only: a heading like "Android" legitimately has none.
        prose = [p for p in g["intro"]] + [b for _, b in g["sections"]]
        bare = [p for p in prose if len(p) > 60 and not dia.search(p)]
        if bare:
            sys.exit("ABORT %s/%s: %d paragraph(s) with no diacritics at all — "
                     "likely stripped or untranslated:\n  %s"
                     % (lang, slug, len(bare), bare[0][:90]))


def m_upper(lang):
    return META[lang]["upper"]


def main():
    lang, batch_dir = sys.argv[1], sys.argv[2]
    if lang not in META:
        sys.exit("ABORT: add %r to META (and STRAY/DIACRITIC if it needs them)"
                 % lang)
    sys.path.insert(0, HERE)
    # guides_i18n.py registers guides_<lang>.py, and build_guides imports
    # guides_i18n — so on the very first run the module this script is about to
    # write is already being imported. Drop an empty stub in first rather than
    # asking the operator to register the language only after generating it,
    # which is an ordering nobody remembers on the next language.
    fname = "guides_%s.py" % lang.replace("-", "_").lower()
    fpath = os.path.join(HERE, fname)
    if not os.path.exists(fpath):
        io.open(fpath, "w", encoding="utf-8").write(
            "# -*- coding: utf-8 -*-\n# stub — replaced on the first successful"
            " run of build_lang_guides.py\nGUIDES_%s = {}\n" % m_upper(lang))
        print("created stub scripts/%s" % fname)
    import build_guides
    order = [g["slug"] for g in build_guides.GUIDES]

    data = {}
    for p in sorted(glob.glob(os.path.join(batch_dir, "b*.json"))):
        batch = json.load(io.open(p, encoding="utf-8"))
        for slug, g in batch.get(lang, {}).items():
            if slug in data:
                sys.exit("ABORT: %s translated twice for %s" % (slug, lang))
            check(lang, slug, g)
            data[slug] = g

    extra = [s for s in data if s not in order]
    if extra:
        sys.exit("ABORT %s: unknown slug(s) %s" % (lang, extra))
    missing = [s for s in order if s not in data]
    print("%-9s %2d/%d translated%s"
          % (lang, len(data), len(order),
             "" if not missing else "  missing: " + ", ".join(missing)))

    have = [s for s in order if s in data]
    m = META[lang]
    body = HEADER % {"name": m["name"], "code": lang,
                     "glossary": m["glossary"], "upper": m["upper"]}
    body += render(data, have)
    io.open(fpath, "w", encoding="utf-8").write(body)
    print("wrote scripts/%s (%d guides)" % (fname, len(have)))


if __name__ == "__main__":
    main()
