#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Assemble the three Chinese guide modules from the translated JSON batches.

The 37 guides are written by hand in two variants and derived into a third:

    zh-Hans   Simplified Mandarin — written from the English source
    yue-Hant  Traditional Cantonese — written from the English source, in
              written Cantonese (嘅/係/喺/唔/咗/啲/佢/冇/畀), not Mandarin
    zh-Hant   Traditional Mandarin — OpenCC s2twp over zh-Hans

zh-Hant is derived rather than written because s2twp is a *phrase* conversion:
it does the Taiwan vocabulary swaps (软件→軟體, 数据库→資料庫, 网络→網路) that a
character-by-character conversion misses, and Traditional Mandarin differs from
Simplified Mandarin in nothing else. Cantonese is a different matter — it is a
different language in the grammar and the function words, so no converter
produces it and it is written out in full.

Reads scratch JSON batches (one per guide, `{lang: {slug: {...}}}`) and writes
scripts/guides_zh_hans.py, guides_zh_hant.py and guides_yue_hant.py.

Usage:  python3 scripts/build_chinese_guides.py <batch-dir>
"""
import glob
import io
import json
import os
import re
import sys

import opencc

HERE = os.path.dirname(os.path.abspath(__file__))
CONV = opencc.OpenCC("s2twp")

# ── Why the conversion is not just `CONV.convert(text)` ───────────────────
#
# s2twp is a *phrase* profile, and on this copy it made two kinds of mistake
# that no test and no page load would ever have caught:
#
#   项目 → 專案      right for a software project, wrong for "item", which is
#                    what every one of these guides means by it
#   合并 → 合並      only sometimes: OpenCC's segmenter occasionally swallows
#                    the 并 into the preceding characters and converts it as a
#                    standalone word, so the site's single most important verb
#                    came out two different ways on the same page
#
# So the vocabulary that carries meaning is pinned by hand and hidden from the
# converter behind placeholders; OpenCC only ever sees ordinary prose. TERMS is
# the contract, BANNED is the check that the contract held.
TERMS = {
    # the glossary — these must never be left to a segmenter
    "合并": "合併", "备份": "備份", "笔记": "筆記", "标注": "標註",
    "书签": "書籤", "标签": "標籤", "设备": "裝置", "还原": "還原",
    "浏览器": "瀏覽器", "数据库": "資料庫", "冲突审阅": "衝突檢視",
    "重复项": "重複項", "出版物": "出版物", "聚会": "聚會", "大会": "大會",
    "演讲": "演講", "个人研究": "個人研究", "备份和还原": "備份和還原",
    "希伯来语经卷": "希伯來語經卷", "希腊语经卷": "希臘語經卷",
    # ordinary words s2twp gets wrong or leaves alone
    "项目": "項目", "并排": "並排", "合并前": "合併前", "合并后": "合併後",
    "台设备": "台裝置", "两台": "兩台", "每台": "每台", "一台": "一台",
    "三台": "三台", "哪台": "哪台", "那台": "那台", "这台": "這台",
    # Taiwan vocabulary s2twp gets right but which must survive protection
    "文件": "檔案", "文件夹": "資料夾", "软件": "軟體", "网络": "網路",
    "视频": "影片", "音频": "音訊", "默认": "預設", "设置": "設定",
    "应用程序": "應用程式", "应用": "應用程式",
    "通过": "透過", "发送": "傳送", "屏幕": "螢幕",
    "存储": "儲存", "缓存": "快取", "字节": "位元組", "兆字节": "MB",
}
# Longest first, so "备份和还原" wins over "备份" and "合并前" over "合并".
_TERMS_ORDER = sorted(TERMS, key=len, reverse=True)

# s2twp writes 台 as 臺 everywhere — the form Taiwan's ministries use and
# almost nobody writes on the web, and wrong outright for the Hong Kong reader
# this script also serves. It is a single character with no ambiguity, so it is
# fixed after conversion rather than pinned as a term.
POST = {"臺": "台"}

# Forms that must never appear in the generated Traditional module. Each one is
# a mistake this pipeline actually made; the list only ever grows.
#
# 文件 is deliberately *not* here. As the Simplified word for "file" it must
# become 檔案, which TERMS guarantees — but s2twp also converts 文档 to 文件,
# which is the correct Traditional name for the Documents folder. Banning the
# string would fail the build on a correct page.
BANNED = ["專案", "合並", "臺", "設備", "軟件", "數據庫", "網絡", "視頻"]

# Characters that have no business in Chinese copy. A Cyrillic "материал" once
# reached a Cantonese paragraph and reads as a plausible word at a glance —
# nothing downstream would have objected, so the check lives here.
STRAY = re.compile("[\u0400-\u04FF\u0590-\u06FF\u0E00-\u0E7F"
                   "\uAC00-\uD7AF\u3040-\u30FF]")

HEADER = '''# -*- coding: utf-8 -*-
"""%(desc)s

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["%(code)s"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

%(glossary)s

Generated by scripts/build_chinese_guides.py — edit the JSON batches, not this.
"""

GUIDES_%(upper)s = '''

GLOSSARY = {
    "zh-Hans": """Glossary settled on for all 37 guides:

  backup              备份
  to merge / merge    合并
  notes               笔记
  highlights          标注
  bookmarks           书签
  tags                标签
  device              设备
  to restore          还原
  Personal Study      个人研究
  Backup and Restore  备份和还原
  browser             浏览器
  database            数据库
  Conflict Reviewer   冲突审阅
  duplicate           重复项
  publication         出版物
  meeting             聚会
  convention          大会
  talk                演讲
  Hebrew Scriptures   希伯来语经卷
  Greek Scriptures    希腊语经卷""",
    "zh-Hant": """Derived from the Simplified module with OpenCC's s2twp profile, so
the Taiwan vocabulary is applied as well as the script: 数据库 → 資料庫,
软件 → 軟體, 文件 → 檔案, 网络 → 網路. The glossary is otherwise the
Simplified one converted term for term.""",
    "yue-Hant": """Written Cantonese, not Traditional Mandarin. The vocabulary and
function words are the spoken ones — 嘅 唔 係 喺 咗 啲 佢 冇 畀 睇 攞 —
because a Cantonese reader who wanted Mandarin would have picked the
zh-Hant page from the same language menu.

Glossary settled on for all 37 guides:

  backup              備份
  to merge / merge    合併
  notes               筆記
  highlights          標註
  bookmarks           書籤
  tags                標籤
  device              裝置
  to restore          還原
  Personal Study      個人研究
  Backup and Restore  備份同還原
  browser             瀏覽器
  database            資料庫
  Conflict Reviewer   衝突檢視
  duplicate           重複嘅嘢
  publication         出版物
  meeting             聚會
  convention          大會
  talk                演講
  Hebrew Scriptures   希伯來語經卷
  Greek Scriptures    希臘語經卷""",
}

DESC = {
    "zh-Hans": "Simplified Chinese (Mandarin) copy for the static guide pages, keyed by slug.",
    "zh-Hant": "Traditional Chinese (Mandarin) copy for the static guide pages, keyed by slug.",
    "yue-Hant": "Cantonese copy for the static guide pages, keyed by slug.",
}


def q(s):
    """A Python string literal that keeps CJK readable in the source."""
    return json.dumps(s, ensure_ascii=False)


def render(guides, order):
    out = ["{\n"]
    for slug in order:
        g = guides[slug]
        out.append("\n %s: {\n" % q(slug))
        out.append("  %s: %s,\n" % (q("title"), q(g["title"])))
        out.append("  %s: %s,\n" % (q("h1"), q(g["h1"])))
        out.append("  %s: %s,\n" % (q("description"), q(g["description"])))
        out.append("  \"intro\": [\n")
        for p in g["intro"]:
            out.append("   %s,\n" % q(p))
        out.append("  ],\n")
        for field in ("steps", "sections", "faq"):
            out.append("  \"%s\": [\n" % field)
            for a, b in g[field]:
                out.append("   (%s, %s),\n" % (q(a), q(b)))
            out.append("  ],\n")
        out.append(" },\n")
    out.append("}\n")
    return "".join(out)


def convert_text(s):
    """Simplified → Traditional with the glossary pinned, not guessed."""
    parts, i = [], 0
    while i < len(s):
        for t in _TERMS_ORDER:
            if s.startswith(t, i):
                parts.append(("term", TERMS[t]))
                i += len(t)
                break
        else:
            if parts and parts[-1][0] == "prose":
                parts[-1] = ("prose", parts[-1][1] + s[i])
            else:
                parts.append(("prose", s[i]))
            i += 1
    out = "".join(v if k == "term" else CONV.convert(v) for k, v in parts)
    for a, b in POST.items():
        out = out.replace(a, b)
    return out


def convert(obj):
    if isinstance(obj, str):
        return convert_text(obj)
    if isinstance(obj, list):
        return [convert(x) for x in obj]
    if isinstance(obj, dict):
        return {k: convert(v) for k, v in obj.items()}
    return obj


def main():
    batch_dir = sys.argv[1]
    sys.path.insert(0, HERE)
    import build_guides
    order = [g["slug"] for g in build_guides.GUIDES]

    data = {"zh-Hans": {}, "yue-Hant": {}}
    for p in sorted(glob.glob(os.path.join(batch_dir, "b*.json"))):
        batch = json.load(io.open(p, encoding="utf-8"))
        for lang, guides in batch.items():
            for slug, g in guides.items():
                if slug in data[lang]:
                    sys.exit("ABORT: %s translated twice for %s" % (slug, lang))
                data[lang][slug] = g

    for lang in ("zh-Hans", "yue-Hant"):
        for slug, g in data[lang].items():
            for m in STRAY.finditer(json.dumps(g, ensure_ascii=False)):
                sys.exit("ABORT %s/%s: stray %r (U+%04X) in Chinese copy"
                         % (lang, slug, m.group(0), ord(m.group(0))))
        missing = [s for s in order if s not in data[lang]]
        extra = [s for s in data[lang] if s not in order]
        if extra:
            sys.exit("ABORT %s: unknown slug(s) %s" % (lang, extra))
        print("%-9s %2d/%d translated%s"
              % (lang, len(data[lang]), len(order),
                 "" if not missing else "  missing: " + ", ".join(missing)))

    # zh-Hant is the Simplified module converted, so it can never drift out of
    # step with the copy it mirrors — but a conversion that is wrong is worse
    # than one that is missing, so every banned form fails the build here.
    data["zh-Hant"] = convert(data["zh-Hans"])
    bad = []
    for slug, g in data["zh-Hant"].items():
        blob = json.dumps(g, ensure_ascii=False)
        for form in BANNED:
            if form in blob:
                bad.append("%s: %r" % (slug, form))
    if bad:
        sys.exit("ABORT: banned Traditional form(s) in the converted copy:\n  "
                 + "\n  ".join(sorted(set(bad))))

    for lang, fname, upper in (("zh-Hans", "guides_zh_hans.py", "ZH_HANS"),
                               ("zh-Hant", "guides_zh_hant.py", "ZH_HANT"),
                               ("yue-Hant", "guides_yue_hant.py", "YUE_HANT")):
        have = [s for s in order if s in data[lang]]
        body = HEADER % {"desc": DESC[lang], "code": lang,
                         "glossary": GLOSSARY[lang], "upper": upper}
        body += render(data[lang], have)
        io.open(os.path.join(HERE, fname), "w", encoding="utf-8").write(body)
        print("wrote scripts/%s (%d guides)" % (fname, len(have)))


if __name__ == "__main__":
    main()
