#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
German pass: bring the ten deepened guides up to the English depth.

Follows the glossary at the top of guides_de.py — du-Anrede, Persönliches
Studium, Sicherung und Wiederherstellung, zusammenführen, Notizen,
Markierungen, Lesezeichen, Schlagwörter, Konfliktvergleich.

Run from the repo root:  python3 scripts/deepen_de.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from deepen_i18n_lib import apply_lang  # noqa: E402

DATA = {
 "merge-jw-library-backups": {
  "sections": [
   ("Was in einer .jwlibrary-Datei wirklich steckt",
    "Eine .jwlibrary-Sicherung ist ein ZIP-Archiv. Benenne eine Kopie in .zip um und öffne sie: Darin findest du userData.db, eine SQLite-Datenbank mit allen Notizen, Markierungen, Lesezeichen und Schlagwörtern, die du je angelegt hast, dazu eine kleine manifest.json, die die Sicherung beschreibt. Deine Notizen liegen in der Tabelle Note, die Markierungen in UserMark und BlockRange, die Lesezeichen in Bookmark, die Schlagwörter in Tag und TagMap. Zu verstehen, dass die Sicherung eine vollständige Datenbank ist und keine Sammlung einzelner Dateien, erklärt alles Weitere auf dieser Seite: deshalb ist eine Wiederherstellung alles oder nichts, und deshalb lassen sich zwei Sicherungen überhaupt kombinieren."),
   ("Warum die Wiederherstellung von JW Library nicht zusammenführen kann",
    "Beim Wiederherstellen liest JW Library deine Sicherung nicht, um das Fehlende zu ergänzen: Es ersetzt die Datenbank des Geräts durch die aus der Datei. Das ist bewusst so gebaut und sicher, weil das Gerät danach in einem bekannten Zustand ist, bedeutet aber, dass die Sicherung des Tablets auf dem Telefon alles verwirft, was das Telefon hatte und das Tablet nicht. Es gibt keine Einstellung, die das ändert, und genau diese Lücke füllt eine Zusammenführung: Sie erzeugt eine einzige Datei, die die Arbeit beider Geräte bereits enthält, sodass jedes Gerät, auf dem du sie wiederherstellst, vollständig ist."),
   ("Wie Duplikate erkannt werden",
    "Jede Notiz, jede Markierung und jedes Lesezeichen trägt eine GUID — eine eindeutige Kennung, die beim Anlegen vergeben und in allen späteren Sicherungen beibehalten wird. Taucht dasselbe Element in zwei Sicherungen auf, tragen beide Kopien dieselbe GUID, es wird als ein Element erkannt und einmal behalten. Deshalb verdoppelt zweimaliges Zusammenführen derselben Dateien nichts, und deshalb kannst du gefahrlos jede Woche erneut zusammenführen. Stimmen die GUIDs überein, der Text aber nicht — dieselbe Notiz auf beiden Geräten bearbeitet —, lässt sich das nicht automatisch klären: Das Element erscheint im Konfliktvergleich mit einem wortgenauen Vergleich, damit du wählst."),
   ("Was nicht in der Sicherung steckt",
    "Eine Sicherung enthält ausschließlich deine persönlichen Studiendaten. Heruntergeladene Publikationen, Bibelübersetzungen, Videos und Audio gehören nicht dazu, und deshalb sind Sicherungsdateien klein — meist wenige Megabyte, selbst nach Jahren. Nach dem Wiederherstellen auf einem neuen Gerät musst du die Publikationen, die du regelmäßig liest, eventuell erneut herunterladen. Nichts von dem, was du geschrieben hast, ist davon betroffen: Notizen sind über Verweise an Publikationen gebunden und hängen sich wieder an, sobald die Publikation vorhanden ist."),
   ("Wenn die Zusammenführung 0 hinzugefügte Notizen meldet",
    "Das ist fast immer richtig und kein Fehler. Es bedeutet, dass alle Notizen der zweiten Datei bereits in der ersten vorhanden waren — üblich, wenn du kürzlich zusammengeführt hast oder ein Gerät schlicht hinter dem anderen zurückliegt. Sieh in die Vorschau: Sie listet auf, was jede Datei beisteuert, bevor irgendetwas geschrieben wird. Wenn du neue Elemente erwartet hast und keine siehst, prüfe, ob du das Gerät nach der gesuchten Studiensitzung gesichert hast — eine Sicherung enthält nur, was im Moment ihrer Erstellung vorhanden war."),
  ],
  "faq": [
   ("Muss ich in einer bestimmten Reihenfolge zusammenführen?",
    "Nein. Die Zusammenführung hängt nicht von der Reihenfolge ab — derselbe Satz Dateien ergibt dasselbe Ergebnis, egal welche du zuerst lädst. Die Reihenfolge bestimmt nur, welche Datei in der Zusammenfassung der Vorschau als Basis gilt."),
   ("Was passiert mit Schlagwörtern, die es nur auf einem Gerät gibt?",
    "Sie werden unverändert übernommen, samt der Verknüpfungen zwischen Schlagwörtern und den Notizen, die sie markieren. Haben beide Geräte ein Schlagwort mit demselben Namen, gilt es als eines und erhält die Notizen von beiden."),
   ("Wie groß ist die zusammengeführte Datei?",
    "Ungefähr so groß wie beide Originale zusammen abzüglich der Duplikate — in der Regel weiterhin nur wenige Megabyte. Sicherungen enthalten keine Publikationsmedien, deshalb bleibt selbst eine stark kommentierte Bibliothek klein genug für eine E-Mail."),
   ("Kann ich eine Wiederherstellung rückgängig machen?",
    "Nicht aus JW Library heraus, und genau deshalb sind deine ursprünglichen Sicherungen wichtig. Die Zusammenführung verändert die geladenen Dateien nie, deine früheren Sicherungen bleiben also exakt erhalten und lassen sich wiederherstellen, wenn du zurück willst."),
  ],
 },
 "transfer-jw-library-notes-new-phone": {
  "intro": [
   "Ein neues Telefon ist der häufigste Moment, in dem Jahre an JW-Library-Notizen verloren gehen — nicht weil die Übertragung schwierig wäre, sondern weil sie bewusst erfolgen muss, bevor das alte Gerät gelöscht wird. Persönliche Studiendaten wandern bei einer normalen Telefonübertragung nicht zuverlässig mit, und JW Library bewahrt davon keine Kopie in irgendeinem Konto auf.",
  ],
  "sections": [
   ("Erledige das, bevor das alte Telefon gelöscht oder abgegeben wird",
    "Die Sicherung muss entstehen, solange das alte Telefon noch läuft und JW Library darauf installiert ist. Sobald das Gerät zurückgesetzt, in Zahlung gegeben oder weitergereicht ist, sind die Notizen mit ihm weg: JW Library hält keine Cloud-Kopie persönlicher Studiendaten vor, und eine Telefonsicherung wie Google One oder eine iCloud-Gerätesicherung stellt oft einen älteren Stand der App-Daten wieder her — oder gar keinen. Erstelle zuerst die .jwlibrary-Datei, bringe sie in Sicherheit und überzeuge dich, dass du sie siehst, bevor du irgendetwas löschst."),
   ("Wie die Datei vom alten Telefon kommt",
    "Unter Android wird die Datei in den von dir gewählten Ordner geschrieben — meist Downloads oder Dokumente — und lässt sich mit jedem Dateimanager verschieben, per E-Mail an dich selbst senden oder in die Cloud legen. Auf dem iPhone erscheint das Teilen-Menü, sobald die Sicherung erstellt ist: Sichere sie in Dateien, schicke sie per AirDrop an das neue Telefon oder sende sie dir selbst. Die Methode spielt keine Rolle und kann die Datei nicht beschädigen: Eine .jwlibrary ist ein einzelnes Archiv, das entweder vollständig ankommt oder gar nicht."),
   ("Warum eine Übertragungs-App zwischen Telefonen nicht reicht",
    "Werkzeuge wie Smart Switch, Auf iOS übertragen oder eine iCloud-Wiederherstellung kopieren Apps und Systemdaten, doch app-eigene Datenbanken werden häufig übersprungen, unvollständig übernommen oder von einem älteren Zeitpunkt wiederhergestellt. Die Lücke fällt regelmäßig erst Wochen später auf, wenn das alte Telefon längst weg ist. Behandle die .jwlibrary-Datei als die maßgebliche Kopie und die Telefonübertragung als Bequemlichkeit: Bringt sie deine Notizen zufällig mit, kostet es nichts, deine eigene Sicherung darüber wiederherzustellen."),
   ("Prüfe, ob die Übertragung wirklich geklappt hat",
    "Öffne nach dem Wiederherstellen auf dem neuen Telefon zwei oder drei kürzlich kommentierte Publikationen und vergewissere dich, dass Notizen, Markierungsfarben und Lesezeichen vorhanden sind. Schneller geht es, wenn du die Sicherungsdatei selbst im Browser öffnest, bevor du das alte Gerät löschst: Du siehst jede Notiz, jede Markierung und jedes Lesezeichen darin und weißt damit, was erscheinen sollte. Lösche das alte Telefon erst, wenn das neue geprüft ist."),
   ("Wenn du zugleich auf Tablet oder Computer umziehst",
    "Dieselbe Datei passt überall. Richtest du neues Telefon und Tablet gleichzeitig ein, stelle dieselbe .jwlibrary-Datei auf beiden wieder her, dann starten sie identisch. Danach laufen sie wieder auseinander, je nachdem, worauf du studierst — es lohnt sich also, jetzt zu entscheiden, ob du sie regelmäßig zusammenführst oder eines als Hauptgerät behandelst."),
   ("Wenn auf dem neuen Telefon schon Notizen liegen",
    "Das passiert, wenn man das neue Gerät eine Woche nutzt, bevor man sich um den Umzug kümmert. Eine direkte Wiederherstellung würde diese Arbeit durch die Daten des alten Telefons ersetzen. Sichere zuerst das neue Telefon, führe diese Datei mit der Sicherung des alten zusammen und stelle das Ergebnis wieder her — beide Notizbestände landen in einer Bibliothek, statt dass einer den anderen überschreibt."),
   ("Was zu tun ist, sobald das neue Telefon läuft",
    "Prüfe, bevor du dich von etwas trennst. Öffne auf dem neuen Telefon einige kürzlich kommentierte Publikationen und bestätige, dass Notizen, Farben und Lesezeichen da sind; erst danach löschst oder gibst du das alte Gerät ab — in dieser Reihenfolge und nie umgekehrt. Wenn alles steht, lege eine Sicherung außerhalb des Telefons ab, denn die Situation, die dich auf diese Seite geführt hat, kommt beim nächsten Wechsel wieder."),
  ],
  "faq": [
   ("Kann ich meine Notizen holen, wenn das alte Telefon schon weg ist?",
    "Nur wenn irgendwo eine .jwlibrary-Datei existiert — in Dateien, Downloads, einer E-Mail an dich selbst oder in der Cloud. Ohne sie gibt es nichts wiederherzustellen, denn persönliche Studiendaten liegen ausschließlich auf dem Gerät."),
   ("Brauchen beide Telefone dieselbe JW-Library-Version?",
    "Sie müssen nicht exakt übereinstimmen, aktualisiere das neue Telefon aber vor dem Wiederherstellen auf die aktuelle Version. Eine von einer neueren Version erstellte Sicherung kann ein Datenbankschema nutzen, das eine ältere App nicht versteht."),
   ("Muss ich meine Publikationen erneut herunterladen?",
    "In der Regel ja — Publikationsmedien gehören nicht zur Sicherung. Deine Notizen hängen sich wieder an jede Publikation, sobald sie heruntergeladen ist, es geht also nichts Geschriebenes verloren."),
   ("Wie lange dauert das Ganze?",
    "Ein paar Minuten. Die Sicherung ist in Sekunden erstellt, das Verschieben hängt von der Methode ab, und das Wiederherstellen geht schnell. Am längsten dauert das erneute Herunterladen der Publikationen, und das kann im Hintergrund laufen."),
   ("Geht das ohne WLAN?",
    "Die Übertragung selbst ja, per AirDrop oder Kabel. Das erneute Herunterladen der Publikationen auf dem neuen Gerät braucht eine Verbindung."),
  ],
 },
 "backup-jw-library": {
  "intro": [
   "Alles, was du in JW Library markiert hast — jede Notiz, jede Markierung, jedes Lesezeichen und Schlagwort — existiert an genau einem Ort: auf dem Gerät in deiner Hand. Es gibt kein Konto, das eine Kopie hält, und keine automatische Cloud-Synchronisierung. Eine Sicherung ist das Einzige, was zwischen einer über Jahre aufgebauten Studienbibliothek und einem verlorenen, zurückgesetzten oder getauschten Telefon steht.",
  ],
  "sections": [
   ("Was die Datei enthält und was nicht",
    "Die Sicherung bewahrt deine persönlichen Studiendaten: Notizen, Markierungen samt Farben, Lesezeichen, Schlagwörter und die Antworten, die du in die Felder der Studienfragen getippt hast. Sie bewahrt keine Publikationen — weder Bibeln noch Zeitschriften, Bücher, Videos oder Audio. Deshalb belegt eine Sicherung von Jahren des Studiums nur wenige Megabyte, und deshalb lädst du nach dem Wiederherstellen auf einem neuen Gerät Publikationen nach, während jede geschriebene Notiz schon wieder an ihrem Platz ist."),
   ("Wie viele Sicherungen du behalten solltest",
    "Mehr als eine. Was Menschen ihre Notizen kostet, ist selten eine verlorene Datei — es ist eine gute Sicherung, die von einer schlechten überschrieben wurde, oder eine Wiederherstellung auf dem falschen Gerät. Da die Dateien klein sind, gibt es keinen Grund, alte zu löschen: Bewahre sie mit Datum in einem Ordner in der Cloud auf. Eine Sicherung von vor einem halben Jahr verliert ihren Wert nicht, auch wenn du neuere hast, denn alles, was du seither versehentlich gelöscht hast, steckt noch darin."),
   ("Wo du sie aufbewahrst",
    "Überall, nur nicht ausschließlich auf dem Gerät selbst. Ein Ordner in Drive, iCloud, Dropbox oder OneDrive deckt den wichtigsten Fall ab: dass das Gerät verloren geht, gestohlen, zurückgesetzt oder beschädigt wird. Die Datei an dich selbst zu mailen funktioniert ebenfalls und hat den nützlichen Nebeneffekt, sie zu datieren. Die Datei enthält deine eigenen Studiennotizen — behandle sie so sorgfältig wie jedes persönliche Dokument."),
   ("Eine Sicherung prüfen, bevor du dich darauf verlässt",
    "Eine Sicherung, die du nie geöffnet hast, ist eine Annahme und kein Sicherheitsnetz. Du kannst eine .jwlibrary-Datei im Browser öffnen und genau sehen, welche Notizen, Markierungen und Lesezeichen darin sind — eine Prüfung von dreißig Sekunden, die aus der Annahme eine Tatsache macht. Das zählt vor allem unmittelbar vor etwas Unumkehrbarem: einem Zurücksetzen auf Werkseinstellungen, einer Abgabe, einer Reparatur oder einem großen Systemupdate."),
   ("Die Momente, vor denen sich eine Sicherung lohnt",
    "Jeder Punkt, an dem das Gerät den Besitzer oder den Zustand wechselt: ein Systemupdate, ein Zurücksetzen, eine Reparatur oder ein Displaytausch, eine Inzahlungnahme oder die Weitergabe an jemanden. Dazu das Ende von allem, was du ungern wiederholen würdest — ein Kongress, eine Zusammenkunftsreihe, eine Zeit der Vorbereitung auf einen Vortrag. Sicherungen sind schnell und billig, die nützliche Gewohnheit knüpft sie also an Ereignisse statt an den Kalender."),
   ("Eine Telefonsicherung ist keine JW-Library-Sicherung",
    "Google One, eine iCloud-Gerätesicherung oder das Übertragungswerkzeug des Herstellers arbeiten auf Geräteebene und behandeln app-eigene Daten uneinheitlich. Regelmäßig stellt sich heraus, dass eine vollständige Telefonwiederherstellung Apps und Einstellungen zurückbrachte, aber nicht die Studiennotizen — oder einen Stand von vor Wochen. Die .jwlibrary-Datei ist die einzige Kopie, deren Inhalt du kontrollierst und prüfen kannst: Behandle die Telefonsicherung als Zugabe, nicht als Plan."),
   ("Eine Gewohnheit daraus machen, die hält",
    "Die Routine, die wirklich hält, hängt an etwas, das du ohnehin tust: sichern, wenn du die Vorbereitung der Woche abschließt, oder am selben Tag, an dem du andere wiederkehrende Dinge erledigst. Speichere immer in denselben Ordner, damit sich die Dateien an einem Ort sammeln, und lass die alten dort liegen. Ein Ordner mit datierten Sicherungen aus mehreren Jahren ist die robusteste Form davon, und ihn zu pflegen kostet Sekunden pro Woche."),
  ],
  "faq": [
   ("Enthält die Sicherung meine heruntergeladenen Publikationen?",
    "Nein. Nur persönliche Studiendaten. Publikationen werden auf dem neuen Gerät erneut heruntergeladen, und deine Notizen hängen sich automatisch wieder an."),
   ("Kann ich eine Sicherung öffnen, um zu sehen, was drin ist?",
    "Ja. Du kannst eine .jwlibrary-Datei im Browser öffnen und alle Notizen, Markierungen und Lesezeichen durchsehen, ohne etwas zu installieren und ohne dass die Datei dein Gerät verlässt."),
   ("Laufen Sicherungen ab?",
    "Nein. Eine .jwlibrary-Datei bleibt unbegrenzt wiederherstellbar. Stelle in einer aktuellen Version von JW Library wieder her statt in einer alten, denn die App liest ältere Sicherungsformate, aber keine neueren."),
   ("Soll ich vor jeder Zusammenkunft sichern?",
    "Nicht nötig. Knüpfe Sicherungen an Ereignisse, die Daten kosten könnten — Updates, Reparaturen, neue Geräte — plus einen regelmäßigen Rhythmus, der dazu passt, wie viel Studium du ungern wiederholen würdest."),
   ("Lohnt es sich, Sicherungen von vor Jahren zu behalten?",
    "Ja. Sie sind klein, und alles, was du seither versehentlich gelöscht hast, steckt noch darin."),
  ],
 },
 "jw-library-android-to-iphone": {
  "intro": [
   "Der Wechsel zwischen Android und iPhone klingt nach dem schwierigen Fall und ist der einfache. JW Library schreibt auf jeder Plattform dasselbe Sicherungsformat, eine Studienbibliothek von Android nach iOS zu bringen ist also derselbe Vorgang wie zwischen zwei Android-Telefonen: keine Umwandlung, kein Exportformat zur Auswahl, nichts, was unterwegs verloren geht.",
  ],
  "sections": [
   ("Warum das Format auf beiden Plattformen identisch ist",
    "JW Library nutzt überall dasselbe Sicherungsformat — Android, iOS, iPadOS und Windows. Eine .jwlibrary-Datei ist ein ZIP mit einer SQLite-Datenbank, die dieselben Tabellen und dasselbe Schema hat, unabhängig davon, welches Gerät sie geschrieben hat. Es gibt keinen Umwandlungsschritt, kein Hin und Her aus Export und Import und nichts Plattformspezifisches in der Datei. Eine Android-Sicherung stellt sich auf einem iPhone genauso wieder her wie eine iPhone-Sicherung."),
   ("Der einzige Teil, der sich wirklich unterscheidet",
    "Nicht die Datei — nur der Zugriff darauf. Unter Android wird die Sicherung in einen Ordner deiner Wahl gespeichert und lässt sich mit jedem Dateimanager verschieben. Auf dem iPhone läuft sie über das Teilen-Menü nach Dateien, AirDrop oder wohin du möchtest. Die Reibung beim Plattformwechsel liegt immer in diesem Handhabungsschritt, nie in der Kompatibilität. E-Mail, Cloud oder AirDrop funktionieren gleichermaßen; das Archiv kommt vollständig an oder gar nicht."),
   ("Markierungsfarben, Schlagwörter und Studienantworten",
    "Alles bleibt erhalten. Markierungsfarben werden als numerischer Index gespeichert — Gelb, Grün, Blau, Rosa, Orange und Violett — und sehen auf jeder Plattform gleich aus. Schlagwörter und die Verknüpfungen zwischen Schlagwörtern und Notizen kommen mit, ebenso die in die Studienfragen getippten Antworten. Was du nach dem Wiederherstellen auf dem iPhone siehst, ist das, was du auf dem Android-Gerät hattest."),
   ("Wenn iOS dich die Datei nicht auswählen lässt",
    "Sichere die Datei zuerst in der App Dateien und wähle sie von dort, statt aus einem Mailanhang oder der Vorschau einer Messenger-App. Manche Apps übergeben iOS eine temporäre Vorschaukopie statt der echten Datei, und die kann JW Library nicht öffnen. Kam die Datei als Anhang, tippe sie an, wähle In Dateien sichern und stelle von dort wieder her."),
   ("Richte das iPhone ein, bevor du wiederherstellst",
    "Installiere JW Library aus dem App Store und aktualisiere es auf die aktuelle Version, bevor du etwas wiederherstellst. Eine von einer neueren Version geschriebene Sicherung kann ein Datenbankschema nutzen, das eine ältere Version nicht versteht — die Wiederherstellung wird dann schlicht abgelehnt. Eine Anmeldung ist nirgends nötig: Persönliche Studiendaten stecken in der Datei, die du wiederherstellst, nicht in einem Konto."),
   ("Wenn du auf dem iPhone schon zu studieren begonnen hast",
    "Sichere zuerst das iPhone. Die Android-Datei direkt darüber wiederherzustellen würde alles ersetzen, was du seit dem Wechsel geschrieben hast. Beide Sicherungen zusammenzuführen ergibt eine Datei mit beidem, die du dann wiederherstellst — der Android-Verlauf und die neuen iPhone-Notizen landen in derselben Bibliothek."),
   ("Beide Telefone danach weiterbenutzen",
    "Manche behalten das alte Android-Gerät als Zweitlesegerät, statt es auszumustern. Das geht, aber beide laufen auseinander, sobald du auf beiden kommentierst, denn zwischen ihnen gibt es keine Synchronisierung. Wenn du beide nutzen willst, plane ein, ihre Sicherungen regelmäßig zusammenzuführen, statt anzunehmen, sie blieben gleich."),
   ("Nach dem Wechsel",
    "Gib dem iPhone Zeit, die Publikationen, die du am meisten nutzt, erneut zu laden, und prüfe dann einige kommentierte, um zu bestätigen, dass alles angekommen ist: Notizen, Markierungsfarben, Lesezeichen und Schlagwörter. Behalte die Android-Sicherungsdatei auch nach abgeschlossenem Wechsel: Sie ist eine datierte Momentaufnahme deiner Bibliothek, und sie zu behalten kostet nichts."),
  ],
  "faq": [
   ("Brauche ich dafür einen Computer?",
    "Nein. AirDrop, E-Mail oder eine beliebige Cloud-App verschiebt die Datei direkt zwischen den beiden Telefonen."),
   ("Funktioniert es auch andersherum, von iPhone zu Android?",
    "Ja, genauso. Dieselben Schritte funktionieren in jede Richtung, auch von und zur Windows-App."),
   ("Braucht das iPhone dieselben heruntergeladenen Publikationen?",
    "Ja, da Publikationsmedien nicht Teil einer Sicherung sind. Die Notizen hängen sich wieder an jede Publikation, sobald sie geladen ist."),
   ("Muss ich das Android-Telefon danach behalten?",
    "Nein, sobald du geprüft hast, dass die Notizen auf dem iPhone sind. Sieh dir einige kommentierte Publikationen an, bevor du das alte Gerät löschst oder abgibst."),
   ("Werden auch die Antworten auf Studienfragen übertragen?",
    "Ja. Getippte Antworten gehören zu den persönlichen Studiendaten und kommen mit allem anderen mit."),
   ("Besteht beim Wechsel ein Risiko, Notizen zu verlieren?",
    "Nicht, wenn du die Android-Sicherung behältst. Die Wiederherstellung schreibt auf das iPhone und verändert die gelesene Datei nie, das Original bleibt also als Rückfalloption unversehrt. Behalte es, bis du bestätigt hast, dass das iPhone alles hat — und am besten auch danach."),
   ("Was, wenn das Android-Telefon keine Sicherung erstellt?",
    "Prüfe zuerst den freien Speicher, denn die App braucht Platz zum Schreiben. Versagt die App selbst, hilft meist ein Update oder ein Neustart des Geräts. Die Daten bleiben unversehrt, während du das klärst."),
  ],
 },
 "sync-jw-library-multiple-devices": {
  "intro": [
   "Die meisten, die auf zwei Geräten studieren, stoßen auf dieselbe Weise auf das Problem: Die auf dem Tablet geschriebenen Notizen sind nicht auf dem Telefon, und die Sicherung des einen auf dem anderen wiederherzustellen würde löschen, was dieses hatte. JW Library bietet keine Synchronisierung, und seine Wiederherstellung ist bewusst alles oder nichts — Geräte gleichzuhalten braucht also eine Routine, keine Einstellung.",
  ],
  "sections": [
   ("Warum es keine echte Synchronisierung gibt",
    "JW Library hat kein Konto, das persönliche Studiendaten von einem Gerät zum anderen trägt. Notizen, Markierungen und Lesezeichen liegen in einer Datenbank auf jedem Gerät und bleiben dort. Der einzige offizielle Weg, sie zu bewegen, ist Sicherung und Wiederherstellung, und eine Wiederherstellung ersetzt die Daten des Zielgeräts, statt sie zu kombinieren. Zwei unabhängig genutzte Geräte laufen daher dauerhaft auseinander, sofern nichts sie zusammenführt — genau darum geht es in der Routine unten."),
   ("Eine Hauptdatei führen",
    "Die Routine funktioniert am besten, wenn du eine zusammengeführte Datei als die aktuelle Hauptdatei behandelst. Sichere in jedem Durchgang alle Geräte, führe diese Sicherungen zusammen und stelle das Ergebnis überall wieder her. Die zusammengeführte Datei wird zur Hauptdatei des nächsten Durchgangs. Die datierten Hauptdateien in der Cloud zu behalten gibt dir zugleich einen Synchronisierungsmechanismus und ein Archiv: Löschst du versehentlich etwas, enthält eine frühere Hauptdatei es noch."),
   ("Was passiert, wenn du ein Gerät eine Weile auslässt",
    "Nichts geht verloren. Ein Gerät, das mehrere Durchgänge ausgelassen hat, trägt schlicht ältere Daten; nimmst du es schließlich hinzu, fügen sich seine Notizen neben allem anderen ein, und wiederholte Elemente werden über die GUID zugeordnet statt verdoppelt. Entscheiden musst du nur bei derselben Notiz, die seit der letzten Zusammenführung auf zwei Geräten bearbeitet wurde — und die erscheint im Konfliktvergleich mit beiden Fassungen nebeneinander."),
   ("Wie oft ist oft genug",
    "Richte es danach, wie viel Arbeit du ungern wiederholen würdest. Wöchentlich passt, wenn du fast täglich auf zwei Geräten studierst; monatlich genügt reichlich, wenn eines gelegentlich genutzt wird. Wichtig ist, es vor allem Unumkehrbaren zu tun — einem Telefonwechsel, einem Zurücksetzen, einer Reparatur —, denn dann wird aus einem Auseinanderlaufen ein Verlust."),
   ("Telefon, Tablet und die Windows-App zusammen",
    "Der Routine ist es gleich, wie viele Geräte beteiligt sind und worauf sie laufen. Sichere jedes, führe alle in einem Durchgang zusammen, stelle die zusammengeführte Datei überall wieder her. Ein Windows-Rechner für die Vorbereitung und ein Telefon für die Zusammenkünfte kombinieren sich genau wie zwei Telefone, denn jede Plattform schreibt dasselbe Sicherungsformat."),
   ("Konflikte verringern, bevor sie entstehen",
    "Konflikte entstehen nur, wenn dieselbe Notiz zwischen zwei Zusammenführungen auf zwei Geräten bearbeitet wird. In der Praxis ist das selten, und es wird noch seltener, wenn du jeweils auf einem Gerät schreibst — überall lesen, aber dort tippen, wo du üblicherweise tippst. Häufiger zusammenzuführen verkleinert außerdem das Zeitfenster, in dem ein Auseinanderlaufen möglich ist, und das wirkt besser, als sich merken zu wollen, welches Gerät die neuere Fassung hat."),
   ("Wo sich die Routine auszahlt",
    "Der Wert des Zusammenführens ist nicht die Ordnung — es ist, dass jedes Gerät zu einer vollständigen Sicherung deiner Studienbibliothek wird. Geht eines verloren oder kaputt, tragen die anderen weiterhin alles, und aus dem schlimmsten Fall von Jahren verlorener Notizen wird eine Unannehmlichkeit. Das ist eine stärkere Position, als jede Sicherungsgewohnheit auf einem einzelnen Gerät sie geben kann."),
  ],
  "faq": [
   ("Was, wenn ich dieselbe Notiz auf zwei Geräten bearbeitet habe?",
    "Beide Fassungen bleiben erhalten, bis du wählst. Der Konfliktvergleich zeigt sie nebeneinander mit einem wortgenauen Vergleich, oder du lässt dir die vollständigere vorschlagen."),
   ("Spielt die Reihenfolge beim Wiederherstellen eine Rolle?",
    "Nein. Ist die zusammengeführte Datei erst erstellt, bringt ihre Wiederherstellung jedes Gerät in denselben vollständigen Zustand, in welcher Reihenfolge auch immer."),
   ("Kann ich drei oder mehr Geräte abgleichen?",
    "Ja. Sichere jedes und lade alle in dieselbe Zusammenführung — es gibt keine an die Gerätezahl gebundene Grenze."),
   ("Lässt sich das automatisieren?",
    "Nicht vollständig, denn JW Library hat keine Synchronisierungsschnittstelle und der Wiederherstellungsschritt geschieht in der App. Die manuelle Routine dauert eingespielt etwa zwei Minuten."),
   ("Muss ich zusammenführen, wenn ich auf dem zweiten Gerät nur lese?",
    "Wenn du dort nie kommentierst, musst du nur gelegentlich darauf wiederherstellen, damit es deine aktuellen Notizen trägt."),
  ],
 },
 "jw-library-notes-missing-after-update": {
  "intro": [
   "JW Library nach einem Update zu öffnen und die Notizen verschwunden vorzufinden ist erschreckend, und in der großen Mehrheit der Fälle sind sie wiederherstellbar. Entscheidend ist, was du in den nächsten Minuten tust — genauer: das Eine nicht zu tun, das aus einer behebbaren Lage einen endgültigen Verlust macht.",
  ],
  "sections": [
   ("Zuerst: Erstelle jetzt noch keine neue Sicherung",
    "Sind die Notizen verschwunden, widerstehe dem Reflex, sofort zu sichern. Eine Sicherung hält den aktuellen Zustand fest, und wenn der aktuelle Zustand der leere ist, riskierst du, die gute Datei zu überschreiben, die du bereits hattest. Finde zuerst heraus, welche Sicherungen existieren — in Downloads, Dateien, der E-Mail oder der Cloud — und entscheide erst dann. Nichts auf dem Gerät wird durch eine hastige Sicherung besser."),
   ("Warum ein Update so wirken kann, als seien Notizen weg",
    "Die übliche Ursache ist kein Löschen. Ein Update kann die App auf eine frische, leere Datenbank zeigen lassen, während die alte noch auf dem Speicher liegt; eine Neuinstallation — auch eine, die ein halb fehlgeschlagenes Store-Update selbst ausgelöst hat — startet die App bei null; und auf gemeinsam genutzten Geräten oder solchen mit mehreren Profilen kann die App unter einem anderen Profil laufen. In allen Fällen sind die Notizen weniger gelöscht als nicht geladen, und deshalb bringt eine Wiederherstellung aus einer Sicherung meist alles sauber zurück."),
   ("Eine alte Sicherung zurückholen, ohne neue Arbeit zu verwerfen",
    "Hast du seit der Sicherung studiert, tauscht eine einfache Wiederherstellung einen Verlust gegen einen anderen: Sie bringt die alten Notizen zurück und entfernt alles Neuere. Der Ausweg ist, den aktuellen Zustand in eine eigene Datei zu sichern, diese mit der älteren Sicherung zusammenzuführen, sodass beide Notizbestände in einer Datei stehen, und das Ergebnis wiederherzustellen. Du hast dann die zurückgeholten und die neuen Notizen zusammen, statt wählen zu müssen."),
   ("Wenn die App sich selbst neu installiert hat",
    "Eine Neuinstallation leert den app-eigenen Speicher: Alles, was nicht in einer Sicherung steht, ist unwiederbringlich — es gibt keine Cloud-Kopie als Rückhalt. Prüfe jeden Ort, an dem eine .jwlibrary-Datei gespeichert worden sein könnte, bevor du schließt, es gebe keine: auch den Gesendet-Ordner deiner E-Mail und jeden Cloud-Speicher, den du je genutzt hast. Sobald du eine findest, stelle sie wieder her — und bewahre Sicherungen fortan außerhalb des Geräts auf."),
   ("Wenn alles zurück ist",
    "Sind deine Notizen wiederhergestellt, mach noch eine Sicherung und lege sie außerhalb des Geräts ab — das gerade Erlebte ist das Argument dafür. Musstest du eine alte Sicherung mit dem aktuellen Zustand zusammenführen, behalte auch beide Ausgangsdateien: Sie sind datierte Momentaufnahmen, und mehr davon zu haben war genau das, was die Rettung möglich gemacht hat."),
  ],
  "faq": [
   ("Sind meine Notizen wirklich weg?",
    "Nicht zwangsläufig. Existiert irgendwo eine Sicherung, ist alles darin vollständig wiederherstellbar. Unwiederbringlich ist nur die Arbeit nach der jüngsten Sicherung."),
   ("Kann ich eine alte Sicherung mit dem jetzigen Stand verbinden?",
    "Ja — sichere zuerst den aktuellen Zustand, führe ihn mit der älteren zusammen und stelle das Ergebnis wieder her. Beide Notizbestände landen in derselben Bibliothek."),
   ("Löscht das Wiederherstellen einer alten Sicherung meine neuen Notizen?",
    "Für sich genommen ja, denn eine Wiederherstellung ersetzt die Daten des Geräts. Führe die aktuelle Sicherung zuerst mit der alten zusammen und stelle die zusammengeführte Datei wieder her."),
   ("Soll ich die App neu installieren, um das zu beheben?",
    "Nein — eine Neuinstallation leert den app-eigenen Speicher und nimmt jede Chance, noch Vorhandenes zu retten. Suche zuerst eine vorhandene Sicherung und behandle die Neuinstallation als letztes Mittel, wenn du eine hast."),
  ],
 },
 "recover-jw-library-notes-lost-phone": {
  "intro": [
   "Geht ein Telefon verloren, wird gestohlen oder irreparabel beschädigt, hängt das Überleben deiner JW-Library-Notizen an einer einzigen Frage: Existiert irgendwo außerhalb dieses Geräts eine .jwlibrary-Sicherung? Wenn ja, kommt alles darin zurück. Diese Seite zeigt, wie du eine findest, wie du sie auf einem beliebigen Ersatzgerät wiederherstellst und was zu tun ist, wenn die einzige Sicherung alt ist.",
  ],
  "sections": [
   ("Wo bereits eine Sicherung liegen könnte",
    "Bevor du schließt, es gebe keine, prüfe jeden Ort, an dem eine Datei gespeichert worden sein könnte: die Ordner Downloads und Dokumente jedes Computers, mit dem du das Telefon verbunden hast, deine gesendeten E-Mails, Messenger-Apps, über die du die Datei geschickt haben könntest, und jedes Cloud-Konto, das du nutzt. Viele haben einmal, vor Monaten, eine Sicherung erstellt und es vergessen — und eine Monate alte Sicherung enthält immer noch den weitaus größten Teil einer Studienbibliothek."),
   ("Auf einem anderen Telefon oder einer anderen Plattform wiederherstellen",
    "Das Ersatzgerät muss dem verlorenen nicht entsprechen. Eine Sicherung von einem Android-Telefon stellt sich auf einem iPhone wieder her und umgekehrt, denn das Format ist unter Android, iOS, iPadOS und Windows identisch. Installiere JW Library auf dem neuen Gerät, aktualisiere es auf die aktuelle Version und stelle über Persönliches Studium → Sicherung und Wiederherstellung wieder her."),
   ("Wenn du nur eine alte oder unvollständige Sicherung hast",
    "Stelle sie trotzdem wieder her. Den größten Teil deiner Notizen zurückzubekommen ist kein Trostpreis — es ist das Ergebnis. Findest du später eine zweite, andere Sicherung, lassen sich beide zu einer Datei mit allem aus beiden zusammenführen: Die ältere jetzt wiederherzustellen hindert dich also nicht daran, später zu ergänzen."),
   ("Was sich nicht wiederherstellen lässt",
    "Existiert in keiner Form eine Sicherung, lassen sich persönliche Studiendaten nicht zurückholen. Sie liegen ausschließlich im app-eigenen Speicher auf dem Gerät, und weder JW Library noch eine Cloud-Sicherung auf Telefonebene bewahrt sie zuverlässig. Das gehört klar gesagt, denn es ist der Grund, warum es die Routine auf dieser Seite überhaupt gibt."),
   ("Prüfe, bevor das Gerät aus der Ferne gelöscht wird",
    "Ist das Telefon verloren und nicht zerstört und erwägst du eine Fernlöschung, suche zuerst nach vorhandenen Sicherungen: Das Löschen ist unumkehrbar und nimmt die letzte Möglichkeit, noch eine zu erstellen. Ist das Gerät nur verlegt und weiterhin erreichbar, lässt sich aus der Ferne keine Sicherung erstellen, doch die Daten bleiben unversehrt, solange es weder gelöscht noch zurückgesetzt wird."),
   ("Dafür sorgen, dass das kein zweites Mal passiert",
    "Dass ein verlorenes Telefon Jahre des Studiums kostet, liegt daran, dass die einzige Kopie auf dem Telefon lag. Hast du auf einem Ersatzgerät wiederhergestellt, lege noch am selben Tag eine Sicherung außerhalb des Geräts ab und wiederhole das in einem Rhythmus, den du wirklich hältst. Die Dateien sind klein genug, um sie alle unbegrenzt aufzubewahren."),
   ("Wenn es wirklich keine Sicherung gibt",
    "Dann ist die ehrliche Antwort, dass die Notizen nicht wiederherstellbar sind, und das zu hören ist besser als weiterzusuchen. Was du tun kannst, ist, diesen Verlust zum letzten zu machen: Installiere JW Library auf dem Ersatzgerät und erstelle, bevor du etwas aufgebaut hast, dessen Verlust schmerzen würde, eine Sicherung außerhalb des Geräts. Von da an kostet dich dasselbe Ereignis nichts."),
  ],
  "faq": [
   ("Bewahrt JW Library eine Kopie meiner Notizen in der Cloud auf?",
    "Nein. Persönliche Studiendaten bleiben auf dem Gerät, sofern du nicht selbst eine Sicherungsdatei erstellst."),
   ("Lassen sich Notizen von einem Telefon mit kaputtem Display retten?",
    "Manchmal — wenn das Telefon noch startet und sich bedienen lässt, oder eine Werkstatt die Anzeige ansteuern kann, kann JW Library weiterhin eine Sicherung erstellen. Die Daten sind unversehrt, solange der Speicher es ist."),
   ("Lässt sich eine alte Sicherung noch in der aktuellen App wiederherstellen?",
    "Ja. JW Library liest ältere Sicherungsformate. Aktualisiere zuerst die App und stelle in der aktuellen Version wieder her."),
   ("Ich habe zwei alte Sicherungen gefunden — welche nehme ich?",
    "Keine für sich allein: Führe sie zusammen. Das Ergebnis enthält alles aus beiden, auch das, was in der älteren stand und zum Zeitpunkt der neueren bereits gelöscht war."),
   ("Kann ich vor dem Wiederherstellen sehen, was in einer Sicherung ist?",
    "Ja. Öffne die Datei im Browser und sieh dir zuerst ihre Notizen, Markierungen und Lesezeichen an, damit du weißt, was du wiederherstellst."),
  ],
 },
 "fix-corrupted-jw-library-backup": {
  "intro": [
   "Eine Sicherung, die sich nicht wiederherstellen lässt, ist nicht zwangsläufig eine Sicherung, die deine Notizen verloren hat. Die meisten Dateien, die als beschädigt beschrieben werden, sind strukturell in Ordnung und werden aus einem behebbaren Grund abgelehnt — oder sie wurden beim Übertragen so beschädigt, dass eine frische Kopie es löst. Es lohnt sich, die Ursachen durchzugehen, bevor du die Datei abschreibst.",
  ],
  "sections": [
   ("Was beschädigt meist bedeutet",
    "In der Praxis sind es selten kaputte Daten. Die üblichen Ursachen sind eine beim Übertragen abgeschnittene Datei — verkürzt durch einen fehlgeschlagenen Upload oder eine Messenger-App, die sie komprimiert hat — oder ein unversehrtes Archiv mit inneren Widersprüchen, die die App ablehnt. Da eine .jwlibrary ein ZIP um eine SQLite-Datenbank ist, kann jede der beiden Schichten das Problem sein, und sie brauchen unterschiedliche Lösungen: Eine abgeschnittene Datei lässt sich nicht reparieren und muss neu beschafft werden; eine widersprüchliche Datenbank meist schon."),
   ("Was eine Prüfung tatsächlich kontrolliert",
    "Eine Prüfung stellt fest, ob das Archiv sich öffnet, ob userData.db eine lesbare SQLite-Datenbank ist, die eine Integritätsprüfung besteht, ob das Schema dem entspricht, was JW Library erwartet, und ob das Manifest zu der Datenbank passt, die es beschreibt — einschließlich der Prüfsumme, mit der die App bestätigt, dass die Datei unverändert ist. Eine Abweichung zwischen Manifest und Datenbank gehört zu den häufigsten Gründen, warum eine technisch einwandfreie Sicherung abgelehnt wird, und sie ist direkt behebbar."),
   ("Verwaiste Einträge sind meist harmlos",
    "Die Prüfung einer echten Sicherung meldet oft Einträge, die auf etwas verweisen, das nicht mehr vorhanden ist — etwa eine Markierung, die auf eine verschobene Stelle einer Publikation zeigt. JW Librarys eigene Sicherungen enthalten routinemäßig Hunderte davon und lassen sich klaglos wiederherstellen. Sie sind eine normale Folge davon, dass Publikationen mit der Zeit aktualisiert werden, kein Hinweis auf Schaden, und sie zu entfernen ist nicht nötig, damit die Datei funktioniert."),
   ("Notizen aus einer Datei retten, die sich nicht wiederherstellen lässt",
    "Auch wenn eine Sicherung nicht so weit repariert werden kann, dass JW Library sie annimmt, sind die Notizen darin oft noch lesbar. Die Datei im Browser zu öffnen erlaubt dir, den Notiztext direkt zu sehen und zu kopieren, und macht aus einer unbrauchbaren Datei gerettetes Studienmaterial. Hast du eine zweite, ältere Sicherung, die sich wiederherstellen lässt, kann der lesbare Inhalt der beschädigten mit ihr zusammengebracht werden, statt ihn abzutippen."),
   ("Wenn die Wiederherstellung ohne klare Meldung scheitert",
    "JW Library lehnt eine Datei oft ab, ohne zu erklären, warum. Am häufigsten sind ein Manifest, dessen Prüfsumme nicht mehr zur beschriebenen Datenbank passt, eine beim Übertragen abgeschnittene Datei, oder eine Sicherung, die von einer neueren App-Version geschrieben wurde als der, in die du wiederherstellst. Das Erste ist behebbar, das Zweite verlangt, die Datei erneut von der Quelle zu holen, und das Dritte löst sich, indem du die App vor dem Wiederherstellen aktualisierst."),
   ("Beim nächsten Mal vermeiden",
    "Die meisten Schäden entstehen unterwegs. Verschiebe Sicherungen als Dateien und nicht über irgendetwas, das sie erneut komprimieren könnte, und bevorzuge Cloud, AirDrop oder ein Kabel gegenüber Messenger-Apps. Prüfe nach dem Übertragen, ob die Größe zum Original passt: Eine deutlich kleinere Datei wurde abgeschnitten, und keine Reparatur bringt Bytes zurück, die nie angekommen sind."),
   ("Wenn nichts hilft",
    "Eine Datei, die sich nicht reparieren lässt, kann trotzdem lesbar sein, und Lesen genügt oft — der Notiztext lässt sich direkt retten, auch wenn JW Library die Datei ablehnt. Kombiniere das mit einer älteren Sicherung, die sich wiederherstellen lässt, und du hast meist den größten Teil deiner Bibliothek. Bevor du eine Datei für unbrauchbar erklärst, öffne sie und sieh, was wirklich darin steht."),
  ],
  "faq": [
   ("Gehen beim Reparieren Notizen verloren?",
    "Reparaturen arbeiten auf einer Kopie und betreffen strukturelle Probleme, nicht den Inhalt. Deine Originaldatei wird nie verändert und bleibt verfügbar, falls du neu ansetzen willst."),
   ("Warum ist meine Sicherung beschädigt worden?",
    "Meist wurde die Datei unterwegs verändert — über eine App gesendet, die sie komprimiert oder abgeschnitten hat, oder durch einen Upload, der nicht fertig wurde. Sie erneut von der Quelle zu übertragen löst es in der Regel."),
   ("Kann eine Prüfung Notizen retten, die ich in JW Library gelöscht habe?",
    "Nein. Ist sie in der App gelöscht und eine neue Sicherung erstellt, steht die Notiz nicht mehr in dieser Datei. Eine Sicherung von vor dem Löschen enthält sie noch."),
   ("Sagt mir die Dateigröße, ob sie abgeschnitten ist?",
    "Oft ja. Vergleiche sie mit dem Original, falls du es noch hast; ein deutlicher Unterschied bedeutet, dass die Übertragung nicht abgeschlossen wurde."),
   ("Lässt sich eine Sicherung, die im Browser aufgeht, sicher wiederherstellen?",
    "Garantiert ist das nicht, aber es ist ein starkes Zeichen, dass Archiv und Datenbank in Ordnung sind, was die häufigsten Fehler ausschließt."),
  ],
 },
 "export-jw-library-notes": {
  "intro": [
   "In JW Library geschriebene Notizen sind in der App leicht zu lesen und überall sonst unhandlich — in einem Dokument, in einer Vortragsgliederung, auf Papier oder in den Händen von jemandem, der die App nicht nutzt. Der Export löst das, und die Hauptfrage ist nicht wie, sondern wie viel: Ein gefilterter Export ist fast immer nützlicher als alles auf einmal.",
  ],
  "sections": [
   ("Ein Format wählen",
    "Reiner Text ist am portabelsten und lässt sich sauber in jedes Dokument oder jede E-Mail einfügen. Formatierte Ausgabe bewahrt die Struktur langer Notizen und eignet sich zum Drucken oder Teilen. Willst du die Notizen später wieder in JW Library haben — auf einem anderen Gerät oder in der Bibliothek einer anderen Person —, behalte die .jwlibrary-Datei selbst statt eines Textexports, denn nur sie bewahrt die Verknüpfungen zwischen Notizen, Markierungen, Schlagwörtern und der genauen Stelle in der Publikation, an der sie hängen."),
   ("Nur einen Teil der Bibliothek exportieren",
    "Ein vollständiger Export aus Jahren des Studiums ist selten das, was man will. Vorher einzugrenzen — auf ein Schlagwort, eine Publikation, eine Markierungsfarbe oder einen Zeitraum — ergibt etwas Brauchbares, etwa alle für einen Vortrag markierten Notizen oder alles, was während eines Kongresses entstand. Dieselben Filter, die die Ansicht eingrenzen, grenzen den Export ein: Was du siehst, bekommst du."),
   ("Was mit dem Text mitgeht und was nicht",
    "Ein Export nimmt deine Worte mit. Er nimmt nicht die Anker mit, die eine Notiz an einen bestimmten Absatz einer bestimmten Publikation binden, denn diese Verweise bedeuten nur innerhalb von JW Library etwas. Das ist der praktische Grund, auch Sicherungen zu behalten: Ein Export dient dem Lesen, Drucken und Teilen außerhalb der App, während eine .jwlibrary-Datei die Notizen mit unversehrtem Zusammenhang in eine Bibliothek zurückbringt."),
   ("Alles für einen Vortrag oder eine Aufgabe zusammentragen",
    "Das ist der häufigste Grund zu exportieren. Filtere auf das Schlagwort, die Publikation oder den Zeitraum, unter dem das Material liegt, prüfe das Ergebnis und exportiere nur das. Heraus kommt ein einzelnes Dokument mit den einschlägigen Notizen und den markierten Passagen in der Reihenfolge ihres Auftretens statt einer unhandlichen Ausgabe deiner gesamten Bibliothek."),
   ("Notizen mit jemandem teilen",
    "Hinter Teilen stecken zwei verschiedene Dinge. Will die andere Person deine Notizen lesen, ist ein Textexport das Richtige: Er öffnet sich überall und braucht keine besondere Software. Will sie die Notizen in ihrer eigenen JW Library haben, an denselben Absätzen verankert und mit ihren Schlagwörtern und Farben, dann brauchst du eine .jwlibrary-Datei, denn ein Textexport kann nichts in die App zurückbringen."),
   ("Ein Archiv behalten, das du auch später noch lesen kannst",
    "Exporte lohnen sich auch um ihrer selbst willen. Eine Kopie deiner Studiennotizen in reinem Text wird sich in dreißig Jahren noch mit Software öffnen lassen, die niemand geschrieben hat, und das kann kein app-eigenes Format versprechen. Beides zu behalten — die .jwlibrary zum Wiederherstellen und einen Textexport zum Lesen — kostet fast nichts und deckt beide Zukünfte ab."),
   ("Export oder Sicherung — was du brauchst",
    "Beide beantworten verschiedene Fragen. Ein Export dient dazu, deine Notizen außerhalb von JW Library zu nutzen: lesen, drucken, zitieren, jemandem schicken. Eine .jwlibrary-Sicherung dient dazu, sie nach JW Library zurückzubringen, auf dieses Gerät oder ein anderes, mit jedem Anker, Schlagwort und jeder Farbe. Keines ersetzt das andere, und es spricht nichts dagegen, beides zu haben."),
  ],
  "faq": [
   ("Bekomme ich meine Notizen in Word oder Google Docs?",
    "Ja — als Text exportieren und einfügen. Der Text kommt mit unversehrter Struktur an und lässt sich von dort formatieren."),
   ("Werden Markierungen ebenso exportiert wie Notizen?",
    "Ja, samt der markierten Passage und ihrer Farbe, sodass ein Ausdruck sowohl zeigt, was du markiert, als auch, was du geschrieben hast."),
   ("Kann ich alles auf einmal exportieren?",
    "Ja, auch wenn ein gefilterter Export meist nützlicher ist. Für eine vollständige Kopie lässt sich alles in einem Durchgang exportieren."),
   ("Kann ich die in Studienfragen getippten Antworten exportieren?",
    "Ja. Getippte Antworten gehören zu deinen persönlichen Studiendaten und lassen sich zusammen mit Notizen und Markierungen exportieren."),
   ("Steht im Export, zu welcher Publikation jede Notiz gehört?",
    "Ja, der Export weist aus, woher jede Notiz stammt, auch wenn der zugrunde liegende Anker nur in JW Library funktioniert."),
   ("Verändert ein Export etwas in meiner Bibliothek?",
    "Nein. Ein Export liest deine Daten und schreibt eine separate Datei; in JW Library wird nichts geändert, verschoben oder entfernt."),
   ("Kann ich aus einer Sicherung statt aus der App exportieren?",
    "Ja. Eine .jwlibrary-Datei lässt sich direkt öffnen und ihre Notizen exportieren — nützlich, wenn die gewünschten Notizen in einer alten Sicherung stehen und nicht auf deinem aktuellen Gerät."),
  ],
 },
 "open-jwlibrary-file": {
  "intro": [
   "Eine .jwlibrary-Datei wirkt undurchsichtig, ist es aber nicht. Sie ist ein gewöhnliches ZIP-Archiv um eine gewöhnliche SQLite-Datenbank, was bedeutet: Du kannst deine eigene Sicherung lesen — genau sehen, welche Notizen, Markierungen und Lesezeichen sie enthält — ohne JW Library und ohne irgendetwas zu installieren.",
  ],
  "sections": [
   ("Was die Datei wirklich ist",
    "Eine .jwlibrary-Datei ist ein ZIP-Archiv mit einer anderen Endung. Darin liegen userData.db — eine SQLite-Datenbank mit deinen Notizen, Markierungen, Lesezeichen und Schlagwörtern — und manifest.json, eine kleine Datei, die die Sicherung beschreibt und eine Prüfsumme der Datenbank enthält, mit der JW Library bestätigt, dass die Datei unverändert ist. Nichts daran ist proprietär oder verschlüsselt: Es ist ein Standardarchiv um eine Standarddatenbank."),
   ("Sie ohne JW Library öffnen",
    "Du brauchst weder die App noch sonst eine Software, um deine eigene Sicherung zu lesen. Die Datei im Browser zu öffnen zeigt alle Notizen, Markierungen und Lesezeichen darin, mit Suche und Filtern, und die Datei verlässt dein Gerät nie — sie wird lokal gelesen, nicht hochgeladen. Das ist der schnellste Weg zu bestätigen, dass eine Sicherung enthält, was du glaubst, bevor du zurücksetzt, abgibst oder auf einem neuen Telefon wiederherstellst."),
   ("Von Hand hineinsehen",
    "Wenn dich interessiert, was drin ist, kopiere die Datei, benenne die Kopie in .zip um und öffne sie mit einem beliebigen Archivwerkzeug. Du siehst userData.db und manifest.json. Die Datenbank zu öffnen braucht einen SQLite-Betrachter, und die Tabellen heißen nach dem, was sie enthalten — Note, UserMark, Bookmark, Tag. Arbeite immer auf einer Kopie: Die Datenbank von Hand zu ändern, ohne die Prüfsumme im Manifest zu erneuern, erzeugt eine Datei, die JW Library beim Wiederherstellen ablehnt."),
   ("Sicher bearbeiten",
    "Notizen lassen sich außerhalb der App korrigieren, neu verschlagworten, umfärben oder löschen, und das Ergebnis als neue .jwlibrary-Datei exportieren, die du normal wiederherstellst. Die Regel, die das sicher macht, ist, das Original zu behalten: Bearbeite eine Kopie, stelle die bearbeitete Datei wieder her, und falls etwas nicht wie erwartet ist, liegt das unangetastete Original noch da."),
   ("Eine Sicherung auf dem Telefon lesen",
    "Ein Computer ist nicht nötig. Die Datei in einem mobilen Browser zu öffnen funktioniert genauso, was nützlich ist, wenn die Sicherung schon auf dem Telefon liegt und du ihren Inhalt vor dem Wiederherstellen oder vor dem Löschen des Geräts prüfen willst. Die Datei wird lokal gelesen, das funktioniert also ohne weitere Verbindung als die zum Laden der Seite."),
   ("Warum die Prüfsumme im Manifest zählt",
    "manifest.json hält eine Prüfsumme von userData.db fest. JW Library bestätigt damit, dass die Datenbank seit dem Schreiben der Sicherung unverändert ist — eine Datei, deren Datenbank ohne Neuberechnung der Prüfsumme bearbeitet wurde, wird beim Wiederherstellen abgelehnt. Das ist der häufigste Grund, warum eine von Hand bearbeitete Sicherung nicht mehr funktioniert, und der Grund, warum ein Werkzeug, das das Manifest neu schreibt, sicherer ist als der direkte Griff in die Datenbank."),
   ("Wofür das gut ist",
    "Eine Sicherung lesen zu können ändert, was eine Sicherung wert ist. Du kannst bestätigen, dass eine Datei enthält, was du denkst, bevor du ein Telefon löschst, prüfen, ob eine alte Datei das Wiederherstellen lohnt, eine Notiz finden, von der du weißt, dass du sie geschrieben hast, ohne die App zu durchsuchen, oder Text aus einer Datei retten, die JW Library ablehnt. Nichts davon verlangt, die Datei jemandem anzuvertrauen — sie wird auf deinem eigenen Gerät gelesen."),
  ],
  "faq": [
   ("Kann ich sie einfach in .zip umbenennen?",
    "Ja, auf einer Kopie. Das Umbenennen ändert den Inhalt nicht und lässt jedes Archivwerkzeug zeigen, was darin steckt."),
   ("Verändert das Öffnen die Datei?",
    "Nein. Eine Sicherung zu lesen — im Browser oder in einem Archivwerkzeug — lässt sie Byte für Byte unverändert. Erst Speichern oder Exportieren erzeugt eine neue Datei."),
   ("Muss ich online sein?",
    "Nur zum Laden der Seite. Die Datei wird auf deinem Gerät gelesen und nicht hochgeladen, deine Notizen gehen also nie über das Netz."),
   ("Kann ich eine Sicherung öffnen, die mir jemand geschickt hat?",
    "Ja, das Format ist weder an ein Gerät noch an ein Konto gebunden. Ob du sie wiederherstellen solltest, ist eine andere Frage, denn eine Wiederherstellung ersetzt deine eigene Bibliothek."),
   ("Muss ich etwas installieren, um hineinzusehen?",
    "Nein. Ein Browser genügt zum Lesen der Notizen; nur die manuelle Untersuchung der Datenbank braucht einen SQLite-Betrachter."),
  ],
 },
}

apply_lang("de", DATA, "Was in einer .jwlibrary-Datei wirklich steckt")
