# -*- coding: utf-8 -*-
"""Romanian copy for the static guide pages, keyed by slug.

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["ro"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

Glossary settled on for all 37 guides:

  backup              copie de rezervă
  to merge / merge    a îmbina / îmbinare
  notes               notițe
  highlights          evidențieri
  bookmarks           semne de carte
  tags                etichete
  device              dispozitiv
  file                fișier
  browser             browser
  to restore          a restaura
  to back up          a face o copie de rezervă
  Personal Study      Studiu personal
  Backup and Restore  Copiere de rezervă și restaurare
  database            bază de date
  Conflict Reviewer   verificatorul de conflicte
  duplicate           duplicat
  publication         publicație
  meeting             întrunire
  convention          congres
  talk                cuvântare
  Hebrew Scriptures   Scripturile ebraice
  Greek Scriptures    Scripturile grecești

JW Library, .jwlibrary, JW Sync and jwsync.org are never translated.

Generated by scripts/build_lang_guides.py — edit the JSON batches, not this.
"""

GUIDES_RO = {

 "merge-jw-library-backups": {
  "title": "Cum îmbini copiile de rezervă JW Library de pe două dispozitive",
  "h1": "Cum îmbini copiile de rezervă JW Library de pe două dispozitive",
  "description": "Combină notițele, evidențierile, semnele de carte și etichetele din două sau mai multe copii de rezervă JW Library într-un singur fișier .jwlibrary — gratuit, privat, în browserul tău.",
  "intro": [
   "Dacă studiezi pe mai multe dispozitive — un telefon la sală, o tabletă acasă — fiecare dispozitiv ajunge cu propriile notițe și evidențieri. Funcția Copiere de rezervă și restaurare din JW Library nu le poate combina: restaurarea unei copii înlocuiește tot ce e pe dispozitiv, ștergând munca celuilalt.",
   "JW Sync rezolvă asta. Citește două (sau mai multe) fișiere de rezervă .jwlibrary și îmbină notițele, evidențierile, semnele de carte și etichetele din toate într-un singur fișier nou. Îmbinarea rulează în întregime în browserul tău — fișierele tale nu sunt încărcate niciodată pe vreun server, așa că notițele tale personale de studiu rămân private.",
  ],
  "steps": [
   ("Creează o copie de rezervă pe fiecare dispozitiv", "În JW Library, deschide Studiu personal, atinge meniul cu trei puncte, alege Copiere de rezervă și restaurare, apoi Creează o copie de rezervă. Fă asta pe fiecare dispozitiv. Fiecare produce câte un fișier .jwlibrary."),
   ("Deschide JW Sync", "Mergi la jwsync.org în orice browser — pe telefon, tabletă sau calculator. Nu ai nimic de instalat."),
   ("Încarcă ambele fișiere de rezervă", "Trage (sau alege) fișierele .jwlibrary. JW Sync le citește local, pe dispozitivul tău."),
   ("Verifică previzualizarea de dinainte de îmbinare", "Înainte să se scrie ceva, o previzualizare îți arată exact ce va fi combinat. Dacă aceeași notiță a fost modificată diferit pe fiecare dispozitiv, verificatorul de conflicte îți arată ambele versiuni una lângă alta, cu diferențele cuvânt cu cuvânt, ca să alegi ce păstrezi — sau lasă „Sugerează cea mai bună” să aleagă pentru tine."),
   ("Descarcă fișierul îmbinat și restaurează-l", "Descarcă fișierul .jwlibrary îmbinat, apoi restaurează-l pe fiecare dispozitiv prin Copiere de rezervă și restaurare → Restaurează. Acum ambele dispozitive au biblioteca completă, combinată."),
  ],
  "sections": [
   ("Ce anume se îmbină?", "Notițe, evidențieri, semne de carte, etichete și legăturile dintre ele. Duplicatele sunt detectate automat, așa că restaurarea fișierului îmbinat nu dublează niciodată nimic. Copiile de rezervă de pe Android, iPhone, iPad și aplicația Windows folosesc toate același format și se îmbină liber între ele."),
   ("E sigur?", "Îmbinarea nu modifică niciodată fișierele tale originale — produce o copie de rezervă complet nouă, așa că originalele rămân neatinse ca plasă de siguranță. Și pentru că totul rulează în browser, pe partea clientului, niciun fel de date nu-ți părăsesc dispozitivul."),
   ("Ce se află de fapt într-un fișier .jwlibrary", "O copie de rezervă .jwlibrary este o arhivă ZIP. Redenumește un exemplar în .zip, deschide-l, și vei găsi userData.db — o bază de date SQLite care conține fiecare notiță, evidențiere, semn de carte și etichetă pe care le-ai făcut vreodată — alături de un mic manifest.json care descrie copia de rezervă. Notițele tale stau într-un tabel Note, evidențierile în UserMark și BlockRange, semnele de carte în Bookmark, iar etichetele în Tag și TagMap. Faptul că o copie de rezervă e o bază de date completă, nu un teanc de fișiere răzlețe, explică tot restul acestei pagini: de aceea restaurarea e totul-sau-nimic și de aceea două copii pot fi combinate."),
   ("De ce restaurarea din JW Library nu poate îmbina", "Când restaurezi, JW Library nu îți citește copia de rezervă ca să adauge la ce e deja pe dispozitiv ce lipsește. Înlocuiește baza de date a dispozitivului cu cea din fișier. E o alegere deliberată și sigură — garantează că dispozitivul ajunge într-o stare cunoscută — dar înseamnă că restaurarea copiei de pe tabletă pe telefon aruncă tot ce avea telefonul și tableta nu. Nu există vreo setare care să schimbe asta, și exact acest gol îl umple o îmbinare: produce un singur fișier care conține deja munca ambelor dispozitive, așa că oricare dispozitiv l-ar primi ajunge complet."),
   ("Cum sunt detectate duplicatele", "Fiecare notiță, evidențiere și semn de carte poartă un GUID — un identificator unic atribuit la creare și păstrat în fiecare copie de rezervă de după. Când același element apare în două copii, ambele exemplare poartă același GUID, așa că e recunoscut ca un singur element și păstrat o singură dată. De aceea îmbinarea acelorași două fișiere de două ori nu dublează nimic și de aceea poți reîmbina în siguranță în fiecare săptămână. Acolo unde GUID-urile se potrivesc, dar textul diferă — aceeași notiță modificată pe ambele dispozitive — elementul nu poate fi rezolvat automat, așa că apare în verificatorul de conflicte, cu diferențele cuvânt cu cuvânt, ca să alegi tu."),
   ("Ce nu se află în copia de rezervă", "O copie de rezervă conține doar datele tale personale de studiu. Publicațiile descărcate, traducerile Bibliei, videoclipurile și fișierele audio nu sunt incluse — de aceea fișierele de rezervă sunt mici, de obicei doar câțiva megabytes chiar și pentru o bibliotecă adunată în ani. După ce restaurezi pe un dispozitiv nou s-ar putea să fie nevoie să descarci din nou publicațiile pe care le citești des. Nimic din ce ai scris nu e afectat de asta; notițele sunt ancorate la publicații prin referință, așa că se reatașează imediat ce publicația e prezentă."),
   ("Dacă îmbinarea raportează 0 notițe adăugate", "Aproape întotdeauna e corect, nu o defecțiune. Înseamnă că fiecare notiță din al doilea fișier exista deja în primul — ceva obișnuit dacă ai îmbinat de curând sau dacă un dispozitiv e pur și simplu în urma celuilalt. Verifică previzualizarea de dinainte de îmbinare: îți arată ce aduce fiecare fișier înainte să se scrie ceva. Dacă te așteptai la elemente noi și nu vezi niciunul, asigură-te că ai făcut copia de rezervă a dispozitivului după sesiunea de studiu pe care o cauți, fiindcă o copie conține doar ce exista în clipa în care a fost creată."),
  ],
  "faq": [
   ("Pot îmbina mai mult de două copii de rezervă?", "Da — încarcă atâtea fișiere .jwlibrary câte dispozitive ai. Toate sunt combinate într-o singură copie de rezervă îmbinată."),
   ("Îmbinarea va crea notițe duplicate?", "Nu. Notițele, evidențierile și semnele de carte identice sunt detectate și păstrate o singură dată. Versiunile cu adevărat diferite ale aceleiași notițe apar în verificatorul de conflicte, ca să decizi tu."),
   ("Funcționează între Android și iPhone?", "Da. Formatul .jwlibrary este identic pe Android, iOS, iPadOS și Windows, așa că se îmbină copii de pe platforme diferite fără nicio conversie."),
   ("Trebuie să îmbin într-o anumită ordine?", "Nu. Îmbinarea nu depinde de ordine — același set de fișiere dă același rezultat, indiferent care e încărcat primul. Ordinea influențează doar ce fișier e tratat ca bază în rezumatul previzualizării."),
   ("Ce se întâmplă cu etichetele care există doar pe un dispozitiv?", "Sunt preluate intacte, împreună cu legăturile dintre etichete și notițele pe care le marchează. Dacă ambele dispozitive au o etichetă cu același nume, e tratată ca o singură etichetă și notițele de pe amândouă i se atașează."),
   ("Cât de mare e fișierul îmbinat?", "Cam cât cele două originale la un loc, minus duplicatele — de obicei tot doar câțiva megabytes. Copiile de rezervă nu conțin materialul publicațiilor, așa că până și o bibliotecă plină de adnotări rămâne destul de mică pentru un e-mail."),
   ("Pot anula o restaurare?", "Nu din JW Library, și tocmai de aceea contează să-ți păstrezi copiile de rezervă originale. Îmbinarea nu modifică niciodată fișierele pe care le încarci, așa că cele de dinainte de îmbinare rămân exact cum erau și pot fi restaurate dacă vrei să te întorci."),
  ],
 },
}
