# -*- coding: utf-8 -*-
"""Dutch copy for the static guide pages, keyed by slug.

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["nl"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

Glossary settled on for all 37 guides:

  backup              back-up
  to merge / merge    samenvoegen / samenvoeging
  notes               aantekeningen
  highlights          markeringen
  bookmarks           bladwijzers
  tags                labels
  device              apparaat
  file                bestand
  browser             browser
  to restore          terugzetten
  to back up          een back-up maken
  Personal Study      Persoonlijke studie
  Backup and Restore  Back-up maken en terugzetten
  database            database
  Conflict Reviewer   conflictcontrole
  duplicate           dubbele
  publication         publicatie
  meeting             vergadering
  convention          congres
  talk                lezing
  Hebrew Scriptures   Hebreeuwse Geschriften
  Greek Scriptures    Griekse Geschriften

JW Library, .jwlibrary, JW Sync and jwsync.org are never translated.

Generated by scripts/build_lang_guides.py — edit the JSON batches, not this.
"""

GUIDES_NL = {

 "merge-jw-library-backups": {
  "title": "Zo voeg je JW Library-back-ups van twee apparaten samen",
  "h1": "JW Library-back-ups van twee apparaten samenvoegen",
  "description": "Voeg de aantekeningen, markeringen, bladwijzers en labels van twee of meer JW Library-back-ups samen tot één .jwlibrary-bestand — gratis, privé, in je browser.",
  "intro": [
   "Als je op meer dan één apparaat studeert — een telefoon in de zaal, een tablet thuis — krijgt elk apparaat zijn eigen aantekeningen en markeringen. Met de ingebouwde functie Back-up maken en terugzetten van JW Library krijg je die niet bij elkaar: één back-up terugzetten vervangt alles op het apparaat en wist het werk van het andere apparaat.",
   "JW Sync lost dat op. Het leest twee (of meer) .jwlibrary-back-ups en voegt de aantekeningen, markeringen, bladwijzers en labels daaruit samen tot één nieuwe back-up. Het samenvoegen gebeurt volledig in je browser — je bestanden worden nooit naar een server geüpload, dus je persoonlijke studieaantekeningen blijven privé.",
  ],
  "steps": [
   ("Maak op elk apparaat een back-up", "Open in JW Library Persoonlijke studie, tik op het menu met de drie puntjes, kies Back-up maken en terugzetten en dan Een back-up maken. Doe dit op elk apparaat. Elk apparaat levert een .jwlibrary-bestand op."),
   ("Open JW Sync", "Ga naar jwsync.org in een willekeurige browser — op je telefoon, tablet of computer. Je hoeft niets te installeren."),
   ("Laad beide back-upbestanden", "Sleep de .jwlibrary-bestanden erin of kies ze. JW Sync leest ze lokaal op je apparaat."),
   ("Bekijk het voorbeeld vóór het samenvoegen", "Voordat er iets wordt weggeschreven, laat een voorbeeld precies zien wat er wordt gecombineerd. Is dezelfde aantekening op beide apparaten anders bewerkt, dan zet de conflictcontrole beide versies naast elkaar met een verschil per woord, zodat jij kiest wat je houdt — of laat “Beste voorstellen” het voor je doen."),
   ("Download het samengevoegde bestand en zet het terug", "Download het samengevoegde .jwlibrary-bestand en zet het op elk apparaat terug via Back-up maken en terugzetten → Terugzetten. Beide apparaten hebben nu de volledige, gecombineerde bibliotheek."),
  ],
  "sections": [
   ("Wat wordt er samengevoegd?", "Aantekeningen, markeringen, bladwijzers, labels en hun onderlinge verbanden. Dubbele items worden automatisch herkend, dus het terugzetten van het samengevoegde bestand verdubbelt nooit iets. Back-ups van Android, iPhone, iPad en de Windows-app hebben allemaal dezelfde indeling en laten zich zonder meer samenvoegen."),
   ("Is het veilig?", "Bij het samenvoegen worden je oorspronkelijke bestanden nooit gewijzigd — er komt een gloednieuwe back-up uit, zodat je originelen onaangeroerd achterblijven als terugvaloptie. En omdat alles in de browser op je eigen apparaat draait, verlaat er geen enkel gegeven je apparaat."),
   ("Wat er eigenlijk in een .jwlibrary-bestand zit", "Een .jwlibrary-back-up is een ZIP-archief. Hernoem een kopie naar .zip, open die, en je vindt userData.db — een SQLite-database met elke aantekening, markering, bladwijzer en elk label dat je ooit hebt gemaakt — samen met een kleine manifest.json die de back-up beschrijft. Je aantekeningen staan in een tabel Note, je markeringen in UserMark en BlockRange, je bladwijzers in Bookmark en je labels in Tag en TagMap. Als je eenmaal doorhebt dat de back-up een complete database is en geen verzameling losse bestanden, verklaart dat al het andere op deze pagina: daarom is terugzetten alles-of-niets, en daarom kunnen twee back-ups überhaupt worden gecombineerd."),
   ("Waarom Terugzetten in JW Library zelf niet kan samenvoegen", "Bij het terugzetten leest JW Library je back-up niet in om de ontbrekende items toe te voegen aan wat er al op het apparaat staat. Het vervangt de database van het apparaat door die uit het bestand. Dat is een bewuste, veilige opzet — zo staat het apparaat gegarandeerd in een bekende toestand — maar het betekent wel dat de back-up van je tablet terugzetten op je telefoon alles weggooit wat de telefoon had en de tablet niet. Er is geen instelling die dat verandert, en precies dat gat vult een samenvoeging: er komt één bestand uit dat het werk van beide apparaten al bevat, dus op welk apparaat je het ook terugzet, dat apparaat is compleet."),
   ("Hoe dubbele items worden herkend", "Elke aantekening, markering en bladwijzer draagt een GUID — een unieke aanduiding die bij het maken wordt toegekend en in elke volgende back-up behouden blijft. Komt hetzelfde item in twee back-ups voor, dan dragen beide kopieën dezelfde GUID, dus wordt het als één item herkend en één keer bewaard. Daarom verdubbelt hetzelfde paar bestanden twee keer samenvoegen niets, en daarom kun je gerust elke week opnieuw samenvoegen. Komen de GUID's overeen maar verschilt de tekst — dezelfde aantekening op beide apparaten bewerkt — dan valt het niet automatisch op te lossen en komt het in de conflictcontrole terecht, met een verschil per woord waaruit jij kiest."),
   ("Wat er niet in de back-up zit", "Een back-up bevat alleen je persoonlijke studiegegevens. Gedownloade publicaties, Bijbelvertalingen, video's en audio zitten er niet in, en daarom zijn back-upbestanden klein — meestal een paar megabyte, zelfs bij een bibliotheek van jaren. Na het terugzetten op een nieuw apparaat moet je de publicaties die je regelmatig leest misschien opnieuw downloaden. Aan wat je hebt geschreven verandert dat niets; aantekeningen zijn via een verwijzing aan publicaties gekoppeld, dus ze hechten zich weer vast zodra de publicatie er is."),
   ("Als het samenvoegen 0 toegevoegde aantekeningen meldt", "Dat klopt bijna altijd en wijst zelden op een fout. Het betekent dat elke aantekening in het tweede bestand al in het eerste stond — gebruikelijk als je onlangs hebt samengevoegd, of als het ene apparaat gewoon achterloopt op het andere. Kijk in het voorbeeld vóór het samenvoegen: daarin staat wat elk bestand bijdraagt voordat er iets wordt weggeschreven. Verwachtte je nieuwe items en zie je er geen, controleer dan of je van het apparaat een back-up hebt gemaakt ná de studiesessie die je zoekt, want een back-up bevat alleen wat er op dat moment was."),
  ],
  "faq": [
   ("Kan ik meer dan twee back-ups samenvoegen?", "Ja — laad zoveel .jwlibrary-bestanden als je apparaten hebt. Ze worden allemaal tot één samengevoegde back-up gecombineerd."),
   ("Ontstaan er dubbele aantekeningen door het samenvoegen?", "Nee. Identieke aantekeningen, markeringen en bladwijzers worden herkend en één keer bewaard. Werkelijk verschillende versies van dezelfde aantekening komen in de conflictcontrole terecht, zodat jij beslist."),
   ("Werkt het tussen Android en iPhone?", "Ja. De .jwlibrary-indeling is op Android, iOS, iPadOS en Windows identiek, dus back-ups van verschillende platforms laten zich zonder omzetten samenvoegen."),
   ("Moet ik in een bepaalde volgorde samenvoegen?", "Nee. Het samenvoegen is volgorde-onafhankelijk — dezelfde set bestanden geeft hetzelfde resultaat, welk bestand je ook als eerste laadt. Het enige waar de volgorde iets aan verandert, is welk bestand in de samenvatting van het voorbeeld als uitgangspunt geldt."),
   ("Wat gebeurt er met labels die maar op één apparaat staan?", "Die gaan ongeschonden mee, samen met de koppelingen tussen labels en de aantekeningen waarop ze staan. Hebben beide apparaten een label met dezelfde naam, dan geldt dat als één label en worden de aantekeningen van beide eraan gekoppeld."),
   ("Hoe groot is het samengevoegde bestand?", "Ongeveer zo groot als de twee originelen bij elkaar, min de dubbele items — meestal nog steeds maar een paar megabyte. Back-ups bevatten geen publicatiemedia, dus zelfs een zwaar geannoteerde bibliotheek blijft klein genoeg om te mailen."),
   ("Kan ik een terugzetting ongedaan maken?", "Niet vanuit JW Library zelf, en daarom is het bewaren van je oorspronkelijke back-ups belangrijk. Bij het samenvoegen worden de bestanden die je laadt nooit gewijzigd, dus je back-ups van vóór het samenvoegen zijn er nog precies zoals ze waren en kun je terugzetten als je terug wilt."),
  ],
 },
}
