# -*- coding: utf-8 -*-
"""Indonesian copy for the static guide pages, keyed by slug.

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["id"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

Glossary settled on for all 37 guides:

  backup              cadangan
  to merge / merge    menggabungkan / gabungan
  notes               catatan
  highlights          sorotan
  bookmarks           penanda
  tags                label
  device              perangkat
  file                berkas
  browser             peramban
  to restore          memulihkan
  to back up          mencadangkan
  publication         publikasi
  study               pelajaran

JW Library, .jwlibrary, JW Sync and jwsync.org are never translated.

Generated by scripts/build_lang_guides.py — edit the JSON batches, not this.
"""

GUIDES_ID = {

 "merge-jw-library-backups": {
  "title": "Cara Menggabungkan Cadangan JW Library dari Dua Perangkat",
  "h1": "Cara menggabungkan cadangan JW Library dari dua perangkat",
  "description": "Satukan catatan, sorotan, penanda, dan label dari dua cadangan JW Library atau lebih menjadi satu berkas .jwlibrary — gratis, pribadi, di peramban Anda.",
  "intro": [
   "Kalau Anda belajar di lebih dari satu perangkat — ponsel di balai, tablet di rumah — setiap perangkat akhirnya punya catatan dan sorotannya sendiri. Fitur Cadangan dan Pemulihan bawaan JW Library tidak bisa menyatukannya: memulihkan satu cadangan akan mengganti semua isi perangkat, menghapus hasil kerja perangkat yang lain.",
   "JW Sync mengatasi hal ini. Alat ini membaca dua (atau lebih) berkas cadangan .jwlibrary lalu menggabungkan catatan, sorotan, penanda, dan label dari semuanya menjadi satu berkas cadangan baru. Penggabungan berlangsung sepenuhnya di peramban Anda — berkas Anda tidak pernah diunggah ke server mana pun, jadi catatan pelajaran pribadi Anda tetap pribadi.",
  ],
  "steps": [
   ("Buat cadangan di setiap perangkat", "Di JW Library, buka Pelajaran Pribadi, ketuk menu tiga titik, pilih Cadangan dan Pemulihan, lalu Buat Cadangan. Lakukan ini di setiap perangkat. Masing-masing menghasilkan satu berkas .jwlibrary."),
   ("Buka JW Sync", "Kunjungi jwsync.org di peramban mana pun — di ponsel, tablet, atau komputer Anda. Tidak ada yang perlu dipasang."),
   ("Muat kedua berkas cadangan", "Jatuhkan (atau pilih) berkas .jwlibrary-nya. JW Sync membacanya langsung di perangkat Anda."),
   ("Periksa pratinjau sebelum penggabungan", "Sebelum apa pun ditulis, sebuah pratinjau menunjukkan persis apa yang akan disatukan. Jika catatan yang sama diubah secara berbeda di masing-masing perangkat, Peninjau Konflik menampilkan kedua versinya berdampingan lengkap dengan perbedaan kata demi kata sehingga Anda bisa memilih mana yang disimpan — atau biarkan “Sarankan yang terbaik” memilihkannya untuk Anda."),
   ("Unduh berkas gabungannya lalu pulihkan", "Unduh berkas .jwlibrary gabungannya, lalu pulihkan di setiap perangkat lewat Cadangan dan Pemulihan → Pulihkan. Kini kedua perangkat memuat perpustakaan yang lengkap dan menyatu."),
  ],
  "sections": [
   ("Apa saja yang digabungkan?", "Catatan, sorotan, penanda, label, dan kaitan di antara semuanya. Duplikat dikenali secara otomatis, jadi memulihkan berkas gabungan tidak pernah menggandakan apa pun. Cadangan dari Android, iPhone, iPad, dan aplikasi Windows semuanya memakai format yang sama dan bisa digabungkan dengan bebas."),
   ("Apakah aman?", "Penggabungan tidak pernah mengubah berkas asli Anda — hasilnya adalah cadangan yang benar-benar baru, jadi berkas asli Anda tetap utuh sebagai cadangan pengaman. Dan karena semuanya berjalan di sisi peramban, tidak ada data yang meninggalkan perangkat Anda."),
   ("Apa sebenarnya isi berkas .jwlibrary", "Cadangan .jwlibrary adalah sebuah arsip ZIP. Ganti nama salinannya menjadi .zip lalu buka, dan Anda akan menemukan userData.db — sebuah basis data SQLite yang menyimpan setiap catatan, sorotan, penanda, dan label yang pernah Anda buat — beserta manifest.json kecil yang menjelaskan cadangan itu. Catatan Anda ada di tabel Note, sorotan Anda di UserMark dan BlockRange, penanda Anda di Bookmark, dan label Anda di Tag serta TagMap. Memahami bahwa cadangan itu adalah sebuah basis data utuh, bukan kumpulan berkas lepas, menjelaskan semua hal lain di halaman ini: itulah sebabnya pemulihan bersifat semua-atau-tidak-sama-sekali, dan itu pula sebabnya dua cadangan bisa disatukan."),
   ("Mengapa fitur Pemulihan JW Library sendiri tidak bisa menggabungkan", "Saat Anda memulihkan, JW Library tidak membaca cadangan Anda lalu menambahkan yang belum ada ke isi perangkat. Ia mengganti basis data perangkat dengan yang ada di berkas itu. Itu rancangan yang disengaja dan aman — memastikan perangkat berakhir dalam keadaan yang pasti — tapi artinya memulihkan cadangan tablet Anda ke ponsel akan membuang semua yang ada di ponsel tapi tidak ada di tablet. Tidak ada pengaturan untuk mengubahnya, dan celah itulah yang diisi oleh penggabungan: hasilnya satu berkas yang sudah memuat hasil kerja kedua perangkat, sehingga perangkat mana pun yang Anda pulihkan akan menjadi lengkap."),
   ("Bagaimana duplikat dikenali", "Setiap catatan, sorotan, dan penanda membawa sebuah GUID — pengenal unik yang diberikan saat Anda membuatnya dan dipertahankan di setiap cadangan sesudahnya. Ketika item yang sama muncul di dua cadangan, kedua salinannya membawa GUID yang sama, sehingga dikenali sebagai satu item dan disimpan sekali saja. Inilah sebabnya menggabungkan pasangan berkas yang sama dua kali tidak menggandakan apa pun, dan sebabnya Anda bisa menggabungkan ulang setiap minggu dengan aman. Kalau GUID-nya cocok tapi teksnya berbeda — catatan yang sama diubah di kedua perangkat — item itu tidak bisa diselesaikan otomatis, jadi ia dimunculkan di Peninjau Konflik lengkap dengan perbedaan kata demi kata untuk Anda pilih."),
   ("Apa yang tidak ada di dalam cadangan", "Cadangan hanya membawa data pelajaran pribadi Anda. Publikasi yang diunduh, terjemahan Alkitab, video, dan audio tidak termasuk, itulah sebabnya berkas cadangan berukuran kecil — biasanya hanya beberapa megabita bahkan untuk perpustakaan yang dibangun bertahun-tahun. Setelah memulihkan di perangkat baru, Anda mungkin perlu mengunduh lagi publikasi yang rutin Anda baca. Tulisan Anda tidak terpengaruh sama sekali; catatan tertaut ke publikasi lewat rujukan, jadi semuanya menempel kembali begitu publikasinya ada."),
   ("Kalau penggabungan melaporkan 0 catatan ditambahkan", "Ini hampir selalu benar, bukan kesalahan. Artinya setiap catatan di berkas kedua sudah ada di berkas pertama — hal yang lumrah kalau Anda baru saja menggabungkan, atau kalau satu perangkat memang tertinggal dari yang lain. Periksa pratinjau sebelum penggabungan: di sana tercantum apa yang disumbangkan tiap berkas sebelum apa pun ditulis. Kalau Anda mengharapkan item baru tapi tidak ada, pastikan Anda mencadangkan perangkatnya setelah sesi pelajaran yang Anda cari, sebab cadangan hanya berisi apa yang ada pada saat cadangan itu dibuat."),
  ],
  "faq": [
   ("Bisakah saya menggabungkan lebih dari dua cadangan?", "Bisa — muat sebanyak berkas .jwlibrary yang sesuai dengan jumlah perangkat Anda. Semuanya disatukan menjadi satu cadangan gabungan."),
   ("Apakah penggabungan akan membuat catatan ganda?", "Tidak. Catatan, sorotan, dan penanda yang identik dikenali dan disimpan sekali saja. Versi yang benar-benar berbeda dari catatan yang sama dimunculkan di Peninjau Konflik untuk Anda putuskan."),
   ("Apakah ini bekerja antara Android dan iPhone?", "Ya. Format .jwlibrary sama persis di Android, iOS, iPadOS, dan Windows, jadi cadangan dari berbagai platform bisa digabungkan tanpa konversi apa pun."),
   ("Apakah saya harus menggabungkan dengan urutan tertentu?", "Tidak. Penggabungan tidak bergantung pada urutan — sekumpulan berkas yang sama menghasilkan hasil yang sama, berkas mana pun yang Anda muat lebih dulu. Urutan hanya memengaruhi berkas mana yang dijadikan dasar bagi ringkasan pratinjau."),
   ("Bagaimana dengan label yang hanya ada di satu perangkat?", "Label itu dibawa serta secara utuh, lengkap dengan kaitan antara label dan catatan yang ditandainya. Kalau kedua perangkat punya label dengan nama yang sama, keduanya diperlakukan sebagai satu label dan catatan dari kedua perangkat ditautkan padanya."),
   ("Seberapa besar berkas gabungannya?", "Kira-kira sebesar kedua berkas asli digabungkan, dikurangi duplikatnya — biasanya tetap hanya beberapa megabita. Cadangan tidak memuat media publikasi, jadi perpustakaan yang penuh catatan sekalipun tetap cukup kecil untuk dikirim lewat surel."),
   ("Bisakah pemulihan dibatalkan?", "Tidak dari dalam JW Library, dan itulah sebabnya menyimpan cadangan asli Anda itu penting. Penggabungan tidak pernah mengubah berkas yang Anda muat, jadi cadangan sebelum penggabungan tetap persis seperti semula dan bisa dipulihkan kalau Anda ingin kembali."),
  ],
 },
}
