# -*- coding: utf-8 -*-
"""Swahili copy for the static guide pages, keyed by slug.

Field names mirror build_guides.GUIDES. Anything left out falls back to
English. `group` and `related` are deliberately not translated — the first is
looked up through CHROME["sw"]["groups"], the second is a list of slugs.

Product names stay in Latin script (JW Library, JW Sync, .jwlibrary, Google
Drive, iCloud), matching how they appear in the file system and in the app.

Glossary settled on for all 39 guides:

  backup              nakala rudufu
  to merge / merge    kuunganisha / muunganisho
  notes               madokezo (sing. dokezo)
  highlights          viangazio (sing. kiangazio)
  bookmarks           alamisho
  tags                lebo
  device              kifaa (pl. vifaa)
  file                faili (pl. mafaili)
  browser             kivinjari
  to restore          kurejesha
  to back up          kutengeneza nakala rudufu
  Personal Study      Funzo la Kibinafsi
  Backup and Restore  Nakala Rudufu na Kurejesha
  database            hifadhidata
  Conflict Reviewer   kikagua migongano
  duplicate           nakala iliyojirudia
  publication         chapisho (pl. machapisho)
  meeting             mkutano
  convention          kusanyiko
  talk                hotuba
  Hebrew Scriptures   Maandiko ya Kiebrania
  Greek Scriptures    Maandiko ya Kigiriki

JW Library, .jwlibrary, JW Sync and jwsync.org are never translated.

Generated by scripts/build_lang_guides.py — edit the JSON batches, not this.
"""

GUIDES_SW = {

 "merge-jw-library-backups": {
  "title": "Jinsi ya kuunganisha nakala rudufu za JW Library kutoka vifaa viwili",
  "h1": "Jinsi ya kuunganisha nakala rudufu za JW Library kutoka vifaa viwili",
  "description": "Unganisha madokezo, viangazio, alamisho na lebo kutoka nakala rudufu mbili au zaidi za JW Library kuwa faili moja la .jwlibrary — bila malipo, kwa faragha, ndani ya kivinjari chako.",
  "intro": [
   "Ulijifunza Mnara wa Mlinzi kwenye simu yako na makala tofauti kwenye kompyuta yako kibao. Sasa kila kifaa kina kazi ambayo kingine hakina — na JW Library haiwezi kuvipatanisha. Kurejesha kwake ni kubadilisha kila kitu, si kuunganisha, kwa hiyo nakala rudufu yoyote utakayorejesha itafuta funzo la kifaa kingine. Kwa kutumia programu peke yake, hakuna njia ya kubaki na zote mbili.",
   "Hicho ndicho tovuti hii ilichopo kwa ajili yake. Husoma mafaili mawili (au zaidi) ya .jwlibrary na huunganisha madokezo, viangazio, alamisho na lebo kutoka yote kuwa nakala rudufu mpya moja — kwa hiyo hakuna kinachohitaji kuchaguliwa badala ya kingine. Kuunganisha kwote hufanyika ndani ya kivinjari chako; mafaili yako hayapakiwi kwenye seva yoyote kamwe, kwa hiyo madokezo yako ya funzo la kibinafsi yanabaki ya faragha.",
   "Ndiyo maana pia zoea hili ni la kuzuia badala ya kutibu: mara utakapoanza kuunganisha mara kwa mara, huhitaji tena kukumbuka kurejesha kabla ya kujifunza mahali pengine. Jifunze mahali ulipo, unganisha wakati unaokufaa, na kila kifaa kitafikia usawa.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu kwenye kila kifaa", "Katika JW Library, fungua Funzo la Kibinafsi, gusa menyu ya vitone vitatu, chagua Nakala Rudufu na Kurejesha, kisha Tengeneza nakala rudufu. Fanya hivi kwenye kila kifaa. Kila kimoja hutoa faili la .jwlibrary."),
   ("Fungua JW Sync", "Nenda jwsync.org kwenye kivinjari chochote — kwenye simu, kompyuta kibao au kompyuta yako. Hakuna cha kusakinisha."),
   ("Pakia mafaili yote mawili ya nakala rudufu", "Dondosha (au uchague) mafaili ya .jwlibrary. JW Sync huyasoma ndani ya kifaa chako."),
   ("Kagua hakikisho la kabla ya kuunganisha", "Kabla ya chochote kuandikwa, hakikisho huonyesha hasa kitakachounganishwa. Ikiwa dokezo lilelile lilihaririwa kwa njia tofauti kwenye kila kifaa, kikagua migongano huonyesha matoleo yote mawili kando kwa kando pamoja na tofauti ya kila neno ili uchague la kuhifadhi — au uache “Pendekeza bora” likuchagulie."),
   ("Pakua faili lililounganishwa kisha ulirejeshe", "Pakua faili lililounganishwa la .jwlibrary, kisha ulirejeshe kwenye kila kifaa kupitia Nakala Rudufu na Kurejesha → Rejesha. Sasa vifaa vyote viwili vina maktaba kamili iliyounganishwa."),
  ],
  "sections": [
   ("Ni nini kinachounganishwa?", "Madokezo, viangazio, alamisho, lebo na viunganisho vyake. Nakala zilizojirudia hutambuliwa kiotomatiki, kwa hiyo kurejesha faili lililounganishwa hakuongezi mara mbili chochote. Nakala rudufu kutoka Android, iPhone, iPad na programu ya Windows zote hutumia muundo uleule na huunganishwa bila tatizo."),
   ("Je, ni salama?", "Kuunganisha hakubadilishi kamwe mafaili yako ya awali — hutoa nakala rudufu mpya kabisa, kwa hiyo mafaili yako ya awali yanabaki bila kuguswa kama kimbilio. Na kwa kuwa kila kitu hufanyika ndani ya kivinjari kwenye kifaa chako, hakuna data inayoondoka kwenye kifaa chako."),
   ("Ni nini hasa kilicho ndani ya faili la .jwlibrary", "Nakala rudufu ya .jwlibrary ni kasha la ZIP. Nakili faili, ubadilishe jina la nakala kuwa .zip kisha uifungue, nawe utapata userData.db — hifadhidata ya SQLite yenye kila dokezo, kiangazio, alamisho na lebo uliyowahi kutengeneza — pamoja na manifest.json ndogo inayoeleza nakala rudufu. Madokezo yako yako kwenye jedwali la Note, viangazio vyako kwenye UserMark na BlockRange, alamisho yako kwenye Bookmark, na lebo zako kwenye Tag na TagMap. Kuelewa kwamba nakala rudufu ni hifadhidata kamili, si mkusanyiko wa mafaili yaliyotawanyika, hueleza kila kitu kingine kwenye ukurasa huu: ndiyo maana kurejesha ni yote-au-hakuna, na ndiyo maana nakala rudufu mbili zinaweza kuunganishwa kabisa."),
   ("Kwa nini Kurejesha kwa JW Library kwenyewe hakuwezi kuunganisha", "Unaporejesha, JW Library haisomi nakala yako rudufu kisha kuongeza vipengele vinavyokosekana kwenye vilivyopo kwenye kifaa. Hubadilisha hifadhidata ya kifaa kwa ile iliyo kwenye faili. Hilo ni muundo wa makusudi na salama — huhakikisha kifaa kinaishia katika hali inayojulikana — lakini humaanisha kuwa kurejesha nakala rudufu ya kompyuta yako kibao kwenye simu yako hutupilia mbali kila kitu simu ilichokuwa nacho ambacho kompyuta kibao haikuwa nacho. Hakuna mpangilio wa kubadilisha hili, na hilo ndilo pengo hasa ambalo muunganisho hulijaza: hutoa faili moja ambalo tayari lina kazi ya vifaa vyote viwili, kwa hiyo kifaa chochote utakachorejeshea kinakuwa kamili."),
   ("Jinsi nakala zilizojirudia zinavyotambuliwa", "Kila dokezo, kiangazio na alamisho hubeba GUID — kitambulisho cha kipekee kinachotolewa unapokitengeneza na kinachohifadhiwa katika kila nakala rudufu inayofuata. Kipengele kilekile kinapotokea katika nakala rudufu mbili, nakala zote mbili hubeba GUID ileile, kwa hiyo hutambuliwa kuwa kipengele kimoja na huhifadhiwa mara moja tu. Ndiyo maana kuunganisha mafaili yaleyale mara mbili hakuongezi chochote mara mbili, na ndiyo maana unaweza kuunganisha upya kila wiki bila hofu. Pale GUID zinapolingana lakini maandishi yakatofautiana — dokezo lilelile lililohaririwa kwenye vifaa vyote viwili — kipengele hakiwezi kutatuliwa kiotomatiki, kwa hiyo huletwa kwenye kikagua migongano pamoja na tofauti ya kila neno ili uchague."),
   ("Ni nini kisichokuwemo kwenye nakala rudufu", "Nakala rudufu hubeba data yako ya funzo la kibinafsi pekee. Machapisho yaliyopakuliwa, tafsiri za Biblia, video na sauti havijumuishwi, na ndiyo maana mafaili ya nakala rudufu ni madogo — kwa kawaida megabaiti chache tu hata kwa maktaba iliyojengwa kwa miaka. Baada ya kurejesha kwenye kifaa kipya huenda ukahitaji kupakua tena machapisho unayosoma mara kwa mara. Hakuna ulichoandika kinachoathiriwa na hilo; madokezo yameunganishwa na machapisho kwa marejeo, kwa hiyo hujiunganisha tena mara tu chapisho linapokuwepo."),
   ("Ikiwa muunganisho unaripoti madokezo 0 yameongezwa", "Karibu kila mara hili ni sahihi badala ya kuwa hitilafu. Humaanisha kuwa kila dokezo lililo kwenye faili la pili tayari lilikuwepo kwenye la kwanza — jambo la kawaida ikiwa umeunganisha hivi karibuni, au ikiwa kifaa kimoja kimebaki nyuma ya kingine. Angalia hakikisho la kabla ya kuunganisha: huorodhesha kila faili linachochangia kabla ya chochote kuandikwa. Ikiwa ulitarajia vipengele vipya nawe huoni chochote, thibitisha kuwa ulitengeneza nakala rudufu ya kifaa baada ya kipindi cha funzo unachokitafuta, kwa kuwa nakala rudufu hubeba tu kilichokuwepo wakati ilipotengenezwa."),
  ],
  "faq": [
   ("Je, ninaweza kuunganisha nakala rudufu zaidi ya mbili?", "Ndiyo — pakia mafaili mengi ya .jwlibrary kadiri ya vifaa ulivyo navyo. Yote huunganishwa kuwa nakala rudufu moja iliyounganishwa."),
   ("Je, kuunganisha kutatengeneza madokezo yaliyojirudia?", "Hapana. Madokezo, viangazio na alamisho yanayofanana hutambuliwa na kuhifadhiwa mara moja. Matoleo yaliyo tofauti kikweli ya dokezo lilelile huletwa kwenye kikagua migongano ili wewe uamue."),
   ("Je, hufanya kazi kati ya Android na iPhone?", "Ndiyo. Muundo wa .jwlibrary ni uleule kwenye Android, iOS, iPadOS na Windows, kwa hiyo nakala rudufu kutoka mifumo tofauti huunganishwa bila ubadilishaji wowote."),
   ("Je, ninahitaji kuunganisha kwa mpangilio fulani?", "Hapana. Muunganisho hautegemei mpangilio — mafaili yaleyale hutoa matokeo yaleyale bila kujali ni lipi utakalopakia kwanza. Kitu pekee ambacho mpangilio huathiri ni faili gani linachukuliwa kuwa msingi katika muhtasari wa hakikisho."),
   ("Ni nini hutokea kwa lebo zilizo kwenye kifaa kimoja pekee?", "Huhamishwa zikiwa nzima, pamoja na viunganisho kati ya lebo na madokezo zinazoyaweka alama. Ikiwa vifaa vyote viwili vina lebo yenye jina lilelile, huchukuliwa kuwa lebo moja na madokezo kutoka vyote viwili huambatanishwa nayo."),
   ("Faili lililounganishwa lina ukubwa gani?", "Takriban ukubwa wa mafaili mawili ya awali yakiunganishwa, ukiondoa nakala zilizojirudia — kwa kawaida bado ni megabaiti chache tu. Nakala rudufu hazina maudhui ya machapisho, kwa hiyo hata maktaba yenye madokezo mengi hubaki ndogo vya kutosha kutumwa kwa barua pepe."),
   ("Je, ninaweza kutendua urejeshaji?", "Si kutoka ndani ya JW Library, na ndiyo maana kuhifadhi nakala zako rudufu za awali ni muhimu. Kuunganisha hakubadilishi kamwe mafaili unayopakia, kwa hiyo nakala zako rudufu za kabla ya kuunganisha zinabaki vilevile na zinaweza kurejeshwa ukitaka kurudi nyuma."),
  ],
 },

 "sync-jw-library-multiple-devices": {
  "title": "Jinsi ya kusawazisha JW Library kati ya vifaa vingi",
  "h1": "Jinsi ya kuweka JW Library sawa kati ya vifaa vingi",
  "description": "JW Library haina usawazishaji wa ndani kati ya vifaa. Hii hapa ni rutuba rahisi na ya faragha ya kuweka madokezo, viangazio na alamisho yakiwa yaleyale kwenye simu, kompyuta kibao na kompyuta yako.",
  "intro": [
   "Watu wengi wanaojifunza kwenye vifaa viwili hugundua tatizo kwa njia ileile: madokezo yaliyoandikwa kwenye kompyuta kibao hayapo kwenye simu, na kurejesha nakala rudufu ya kifaa kimoja kwenye kingine kungefuta chochote kifaa hicho kilichokuwa nacho. JW Library haitoi usawazishaji, na Kurejesha kwake ni kwa makusudi yote-au-hakuna, kwa hiyo kuweka vifaa sawa kunahitaji rutuba badala ya mpangilio.",
   "JW Library haisawazishi data ya funzo la kibinafsi kati ya vifaa — hakuna akaunti inayobeba madokezo yako kutoka simu yako hadi kompyuta yako kibao. Njia rasmi ni Nakala Rudufu na Kurejesha, na kurejesha hubadilisha data ya kifaa kabisa. Basi unawezaje kuweka vifaa viwili au vitatu vikiwa vilevile bila kupoteza chochote?",
   "Jibu ni rutuba fupi ya kuunganisha na kurejesha. Ikifanywa kila wiki au kila mwezi, huchukua kama dakika mbili na huweka kila kifaa kikiwa na maktaba yako kamili.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu ya kila kifaa", "Kwenye kila kifaa: Funzo la Kibinafsi → menyu ya vitone vitatu → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu. Unapata faili moja la .jwlibrary kwa kila kifaa."),
   ("Unganisha nakala rudufu kwenye jwsync.org", "Pakia mafaili yote. JW Sync huunganisha madokezo, viangazio, alamisho na lebo kutoka kila kifaa kuwa faili moja la .jwlibrary lililounganishwa — ndani ya kivinjari chako, hakuna kinachopakiwa."),
   ("Rejesha faili lililounganishwa kwenye kila kifaa", "Nakala Rudufu na Kurejesha → Rejesha, kisha uchague faili lililounganishwa. Sasa kila kifaa ni kilekile na kamili."),
   ("Acha JW Sync ikukumbushe", "Washa ukumbusho wa usawazishaji (kila wiki au kila mwezi) katika JW Sync nayo itakugusa bega wakati wa kurudia rutuba unapofika. Pia hukumbuka vifaa vyako vilivyohifadhiwa, kwa hiyo kila raundi huenda haraka zaidi."),
  ],
  "sections": [
   ("Kwa nini usirejeshe tu nakala rudufu mpya zaidi?", "Kwa sababu “mpya zaidi” huakisi kifaa kimoja tu. Ikiwa uliandika madokezo ya mkutano kwenye simu na madokezo ya funzo kwenye kompyuta kibao wiki ileile, kila nakala rudufu ina maudhui ambayo nyingine haina. Kurejesha yoyote juu ya nyingine hupoteza nusu ya kazi yako. Kuunganisha kwanza ndiko kunakofanya rutuba iwe salama."),
   ("Nisawazishe mara ngapi?", "Linganisha na jinsi unavyojifunza. Vifaa viwili vinavyotumika kila siku: kila wiki ni vizuri. Kompyuta kibao inayotoka tu kwa ajili ya mikutano: kila mwezi ni tosha. Gharama ya kusubiri zaidi ni kwamba muunganisho una mengi zaidi ya kuunganisha — hakuna kinachopotea kati ya raundi."),
   ("Kwa nini hakuna usawazishaji wa kweli", "JW Library haina akaunti inayobeba data ya funzo la kibinafsi kati ya vifaa. Madokezo, viangazio na alamisho hukaa kwenye hifadhidata ndani ya kila kifaa na hubaki hapo. Njia pekee rasmi ya kuvihamisha ni Nakala Rudufu na Kurejesha, na kurejesha hubadilisha data ya kifaa lengwa badala ya kuiunganisha. Kwa hiyo vifaa viwili vinavyotumika kivyake hutengana kabisa isipokuwa kitu fulani kiviunganishe — na hilo ndilo lengo lote la rutuba iliyo hapa chini."),
   ("Kuweka faili moja kuu", "Rutuba hii hufanya kazi vizuri zaidi ukichukulia faili moja lililounganishwa kuwa faili kuu la sasa. Kila mzunguko, tengeneza nakala rudufu ya kila kifaa, unganisha nakala hizo pamoja, kisha urejeshe matokeo kila mahali. Faili lililounganishwa kisha huwa faili kuu la mzunguko unaofuata. Kuweka mafaili makuu yenye tarehe kwenye hifadhi ya wingu hukupa njia ya kusawazisha na pia kumbukumbu inayoendelea — ukifuta kitu kwa bahati mbaya, faili kuu la awali bado linakuwa nalo."),
   ("Nini hutokea ukiruka kifaa kwa muda", "Hakuna kinachopotea. Kifaa kilichoachwa nje ya mizunguko kadhaa hubeba tu data ya zamani; unapokijumuisha hatimaye, madokezo yake huungana pamoja na mengine yote na vipengele vilivyojirudia hulinganishwa kwa GUID badala ya kuongezwa mara mbili. Hali pekee inayohitaji uamuzi ni dokezo lilelile lililohaririwa kwenye vifaa viwili tangu vilipounganishwa mwisho, na hilo huletwa kwenye kikagua migongano matoleo yote mawili yakionyeshwa kando kwa kando."),
   ("Mara ngapi ni mara za kutosha", "Linganisha na kiasi cha kazi ambacho ungejali kukirudia. Kila wiki hufaa watu wanaojifunza kwenye vifaa viwili siku nyingi; kila mwezi ni tosha ikiwa kifaa kimoja hutumika mara chache. Jambo muhimu ni kuifanya kabla ya lolote lisiloweza kutenduliwa — kubadili simu, kuiweka upya, kuitengeneza — kwa sababu hapo ndipo utengano unapokuwa hasara."),
   ("Simu, kompyuta kibao na programu ya Windows pamoja", "Rutuba hii haijali ni vifaa vingapi vinavyohusika wala vinavyotumia mfumo gani. Tengeneza nakala rudufu ya kila kimoja, viunganishe vyote kwa mpigo mmoja, kisha urejeshe faili lililounganishwa kila mahali. Kompyuta ya Windows inayotumika kujiandaa na simu inayotumika mikutanoni huunganishwa sawasawa na simu mbili zingeunganishwa, kwa sababu kila mfumo huandika muundo uleule wa nakala rudufu."),
   ("Kupunguza migongano kabla haijatokea", "Migongano hutokea tu wakati dokezo lilelile linahaririwa kwenye vifaa viwili kati ya muunganisho mmoja na mwingine. Kwa vitendo hilo ni nadra, nalo huwa nadra zaidi ukiandika kwenye kifaa kimoja kwa wakati — ukisoma popote, lakini ukiandika pale unapoandika kwa kawaida. Kuunganisha mara nyingi zaidi pia hupunguza dirisha ambalo utengano unaweza kutokea, nako ni suluhisho bora kuliko kujaribu kukumbuka ni kifaa gani kilicho na toleo jipya zaidi."),
   ("Pale rutuba inapolipa", "Faida ya kuweka vifaa vimeunganishwa si unadhifu — ni kwamba kila kifaa huwa nakala rudufu kamili ya maktaba yako ya funzo. Poteza au uvunje kimoja chochote kati yavyo na vingine bado vina kila kitu, jambo linalogeuza hali mbaya zaidi kutoka miaka ya madokezo yaliyopotea kuwa usumbufu tu. Hiyo ni nafasi imara kuliko zoea lolote la nakala rudufu la kifaa kimoja linaloweza kukupa."),
  ],
  "faq": [
   ("Je, JW Sync hufanya kazi chinichini?", "Hapana — ni ukurasa wa wavuti, si huduma iliyosakinishwa. Hakuna kinachochunguza vifaa vyako. Wewe huendesha rutuba unapotaka; ukumbusho wa hiari ni arifa tu."),
   ("Je, ninaweza kusawazisha vifaa vitatu au zaidi?", "Ndiyo. Tengeneza nakala rudufu ya kila kimoja, pakia mafaili yote, unganisha mara moja, kisha urejeshe faili lililounganishwa kila mahali."),
   ("Itakuwaje ikiwa nilihariri dokezo lilelile kwenye vifaa viwili?", "Matoleo yote mawili huhifadhiwa hadi uchague. Kikagua migongano huyaonyesha kando kwa kando pamoja na tofauti ya kila neno, au unaweza kukiacha kipendekeze toleo lililo kamili zaidi."),
   ("Je, mpangilio wa kurejesha unaleta tofauti?", "Hapana. Mara faili lililounganishwa linapotengenezwa, kulirejesha kwenye kila kifaa huweka kila kifaa katika hali ileile kamili, kwa mpangilio wowote unaokufaa."),
   ("Je, ninaweza kuunganisha vifaa vitatu au zaidi?", "Ndiyo. Tengeneza nakala rudufu ya kila kimoja kisha uzipakie zote kwenye muunganisho uleule — hakuna kikomo kinachohusiana na idadi ya vifaa."),
   ("Je, hili linaweza kufanywa kiotomatiki?", "Si kabisa, kwa sababu JW Library haina API ya usawazishaji na hatua ya kurejesha hufanyika ndani ya programu. Rutuba ya mkono huchukua kama dakika mbili ukishaizoea."),
   ("Je, ninahitaji kuunganisha ikiwa ninasoma tu kwenye kifaa cha pili?", "Ikiwa huandiki chochote juu yake, unahitaji tu kurejesha juu yake mara kwa mara ili kibebe madokezo yako ya sasa."),
  ],
 },

 "transfer-jw-library-notes-new-phone": {
  "title": "Jinsi ya kuhamisha madokezo ya JW Library kwenye simu mpya",
  "h1": "Jinsi ya kuhamisha madokezo ya JW Library kwenye simu mpya",
  "description": "Kuhamisha madokezo ya JW Library kwenye simu mpya ni nakala rudufu na urejeshaji, nayo programu hufanya hivyo kwa kama dakika mbili. Hizi hapa ni hatua — pamoja na kesi moja tu ambayo haiwezi kuishughulikia: simu mpya ambayo tayari ina madokezo yake.",
  "intro": [
   "Hili ni rahisi kuliko watu wanavyodhani, wala huhitaji kifaa chochote cha ziada. JW Library ina Nakala Rudufu na Kurejesha ndani yake, nayo hubeba kila dokezo, kiangazio, alamisho na lebo hadi kwenye simu mpya — hata kati ya Android na iPhone. Fanya hivyo wakati kifaa cha zamani bado kinafanya kazi na jambo lote huchukua dakika chache.",
   "Sehemu pekee ya kufanya kwa makusudi ni uhamishaji wenyewe: vifaa vya kuhamisha kutoka simu hadi simu husogeza programu na picha zako, lakini huruka data ya funzo la kibinafsi ya JW Library, kwa hiyo tengeneza faili la nakala rudufu badala ya kudhani litafuatana lenyewe.",
   "Kuna hali moja tu ambayo programu haiwezi kuishughulikia, nayo inafaa kujulikana kabla hujaanza: ikiwa tayari umekuwa ukijifunza kwenye simu mpya, kurejesha nakala rudufu ya simu ya zamani kutafuta kazi hiyo, kwa sababu urejeshaji hubadilisha maktaba ya kifaa kabisa. Ikiwa hiyo ndiyo hali yako, sehemu ya kuunganisha iliyo hapa chini ndiyo unayoitaka.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu kwenye simu ya zamani", "Fungua JW Library → Funzo la Kibinafsi → menyu ya vitone vitatu → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu. Hii huhifadhi faili la .jwlibrary lenye data yako yote ya funzo."),
   ("Sogeza faili hadi kwenye simu mpya", "Jitumie kwa barua pepe, au tumia Google Drive, iCloud, AirDrop au kebo ya USB. Faili ni dogo — kwa kawaida megabaiti chache."),
   ("Rejesha kwenye simu mpya", "Sakinisha JW Library, kisha Funzo la Kibinafsi → Nakala Rudufu na Kurejesha → Rejesha, kisha uchague faili la .jwlibrary. Madokezo, viangazio, alamisho na lebo zote huonekana."),
  ],
  "sections": [
   ("Tayari umeandika madokezo kwenye simu mpya? Unganisha badala ya kuandika juu yake", "Kurejesha hubadilisha chochote kilicho kwenye kifaa. Ikiwa umekuwa ukitumia simu mpya kwa muda nayo ina madokezo yake, usirejeshe juu yake — tengeneza nakala rudufu ya simu mpya pia, kisha uunganishe nakala za zamani na mpya kuwa faili moja kwenye jwsync.org (bila malipo, ndani ya kivinjari chako, hakuna kinachopakiwa) kisha urejeshe faili lililounganishwa. Unabaki na seti zote mbili za madokezo."),
   ("Tatizo la kawaida kwenye iPhone", "Ikiwa faili la nakala rudufu linafika kwenye iPhone likiwa limebadilishwa jina kuwa .zip, libadilishe tena kuwa .jwlibrary kabla ya kurejesha — maudhui yako sawa; kilichobadilika njiani ni kiendelezi tu."),
   ("Fanya hivi kabla simu ya zamani haijafutwa au kuuzwa", "Nakala rudufu lazima itengenezwe wakati simu ya zamani bado inafanya kazi na bado ina JW Library. Mara kifaa kinapowekwa upya, kuuzwa au kupewa mtu mwingine, madokezo huondoka nacho — JW Library haihifadhi nakala ya data ya funzo la kibinafsi wingu, na nakala rudufu ya kiwango cha simu kama Google One au ya kifaa cha iCloud kwa kawaida hurejesha picha ya zamani ya data ya programu, au haihifadhi kabisa. Tengeneza faili la .jwlibrary kwanza, lipeleke mahali salama, kisha uthibitishe unaliona kabla ya kufuta chochote."),
   ("Kutoa faili kwenye simu ya zamani", "Kwenye Android faili huandikwa kwenye folda uliyochagua — kwa kawaida Downloads au Documents — nawe unaweza kulisogeza kwa kidhibiti chochote cha mafaili, kujitumia kwa barua pepe, au kuliweka kwenye hifadhi ya wingu. Kwenye iPhone karatasi ya kushiriki huonekana mara tu nakala rudufu inapotengenezwa: ihifadhi kwenye Files, itume kwa AirDrop hadi simu mpya, au ujitumie. Njia ya kuhamisha haileti tofauti wala haiwezi kuharibu faili; .jwlibrary ni kasha moja ambalo hufika likiwa zima au halifiki kabisa."),
   ("Kwa nini programu ya kuhamisha kutoka simu hadi simu haitoshi", "Vifaa kama Smart Switch, Move to iOS au urejeshaji wa iCloud hunakili programu na data ya mfumo, lakini hifadhidata za ndani za programu mara nyingi hurukwa, hurejeshwa nusunusu, au hurejeshwa kutoka wakati wa zamani. Watu hugundua pengo hilo mara kwa mara wiki kadhaa baadaye, simu ya zamani ikiwa tayari imeondoka. Chukulia faili la .jwlibrary kuwa nakala yenye mamlaka na uhamishaji wa simu kuwa urahisi tu — ikiwa uhamishaji utabahatika kubeba madokezo yako, kurejesha nakala yako rudufu juu yake hakugharimu chochote."),
   ("Hakikisha uhamishaji ulifanikiwa kweli", "Baada ya kurejesha kwenye simu mpya, fungua machapisho mawili au matatu uliyoandika ndani yake hivi karibuni kisha uthibitishe kuwa madokezo, rangi za viangazio na alamisho vyote vipo. Ukaguzi wa haraka zaidi ni kufungua faili la nakala rudufu lenyewe kwenye kivinjari chako kabla ya kufuta kifaa cha zamani — unaweza kuona kila dokezo, kiangazio na alamisho lililomo, kwa hiyo unajua kinachopaswa kuonekana. Futa simu ya zamani baada tu ya kuthibitisha mpya."),
   ("Kuhamia kompyuta kibao au kompyuta wakati uleule", "Faili lilelile hufanya kazi kila mahali. Ikiwa unaanzisha simu mpya na kompyuta kibao pamoja, rejesha faili lilelile la .jwlibrary kwenye vyote viwili navyo huanza vikiwa vinalingana. Kuanzia hapo vitatengana tena kadiri unavyojifunza kwenye kila kimoja, kwa hiyo inafaa kuamua sasa kama utaviweka vikiunganishwa mara kwa mara au kuchukulia kimoja kuwa kifaa kinachohesabika."),
   ("Ikiwa simu mpya tayari ina madokezo juu yake", "Hili hutokea unapotumia kifaa kipya kwa wiki moja kabla ya kufikia uhamishaji. Kurejesha moja kwa moja kungebadilisha kazi hiyo kwa data ya simu ya zamani. Tengeneza nakala rudufu ya simu mpya kwanza, unganisha faili hilo na nakala rudufu ya simu ya zamani, kisha urejeshe matokeo yaliyounganishwa — seti zote mbili za madokezo huishia kwenye maktaba moja badala ya moja kuandika juu ya nyingine."),
   ("Cha kufanya simu mpya ikishafanya kazi", "Thibitisha kabla ya kutupa chochote. Fungua machapisho machache uliyoandika ndani yake hivi karibuni kwenye simu mpya kisha uthibitishe kuwa madokezo, rangi na alamisho vyote vipo, kisha ndipo ufute au uuze kifaa cha zamani — kwa mpangilio huo, kamwe si kinyume chake. Ukishatulia, weka nakala rudufu mahali fulani nje ya simu, kwa sababu hali iliyokuleta kwenye ukurasa huu itarudi tena wakati wa simu inayofuata."),
  ],
  "faq": [
   ("Je, hii itahamisha pia machapisho niliyopakua?", "Nakala rudufu hubeba data yako ya funzo la kibinafsi — madokezo, viangazio, alamisho, lebo na orodha za kucheza. Machapisho hupakuliwa tu upya kwenye simu mpya."),
   ("Je, inaleta tofauti ikiwa simu zina matoleo tofauti ya Android?", "Hapana. Muundo wa .jwlibrary ni uleule kila mahali, ikiwa ni pamoja na kati ya matoleo ya Android na kati ya Android na iPhone."),
   ("Je, ninaweza kuhamisha madokezo yangu ikiwa simu ya zamani tayari imeondoka?", "Ni ikiwa tu nakala rudufu ya .jwlibrary ipo mahali fulani — kwenye Files, Downloads, barua pepe uliyojitumia au hifadhi ya wingu. Bila hiyo hakuna cha kurejesha kutoka, kwa sababu data ya funzo la kibinafsi huhifadhiwa kwenye kifaa pekee."),
   ("Je, simu zote mbili zinahitaji toleo lilelile la JW Library?", "Haziitaji kufanana kabisa, lakini isasishe simu mpya hadi toleo la sasa kabla ya kurejesha. Nakala rudufu iliyotengenezwa na toleo jipya zaidi inaweza kutumia muundo mpya wa hifadhidata ambao programu ya zamani haielewi."),
   ("Je, itanibidi kupakua machapisho yangu tena?", "Kwa kawaida ndiyo — maudhui ya machapisho si sehemu ya nakala rudufu. Madokezo yako hujiunganisha tena na kila chapisho mara tu linapopakuliwa, kwa hiyo hakuna ulichoandika kinachopotea wakati huo."),
   ("Jambo lote huchukua muda gani?", "Dakika chache. Kutengeneza nakala rudufu huchukua sekunde, kusogeza faili hutegemea njia yako, na kurejesha huenda haraka. Kupakua machapisho upya baadaye ndiko kunachukua muda mrefu zaidi nako kunaweza kuendelea chinichini."),
   ("Je, ninaweza kufanya hivi bila Wi-Fi?", "Uhamishaji wenyewe ndiyo, kupitia AirDrop au kebo. Kupakua machapisho upya kwenye kifaa kipya kunahitaji muunganisho."),
  ],
 },

 "jw-library-android-to-iphone": {
  "title": "Hamisha JW Library kutoka Android kwenda iPhone (ukiweka madokezo yote)",
  "h1": "Kuhamisha JW Library kutoka Android kwenda iPhone au iPad — ukiweka kila dokezo",
  "description": "Muundo wa nakala rudufu wa .jwlibrary ni uleule kwenye Android na iOS. Jinsi ya kuhamisha madokezo, viangazio na alamisho kati ya mifumo — na jinsi ya kuunganisha ikiwa vifaa vyote viwili vina madokezo.",
  "intro": [
   "Kuhama kati ya Android na iPhone kunasikika kama kesi ngumu, kumbe ndiyo rahisi zaidi. JW Library huandika muundo uleule wa nakala rudufu kwenye kila mfumo inayofanya kazi juu yake, kwa hiyo kuhamisha maktaba ya funzo kutoka Android kwenda iOS ni kazi ileile ya kuihamisha kati ya simu mbili za Android — hakuna ubadilishaji, hakuna muundo wa kuhamisha wa kuchagua, hakuna kinachopotea njiani.",
   "Kubadili mfumo ndio wakati ambao watu huogopa kupoteza miaka ya madokezo ya funzo — programu za kuhamisha kutoka Android kwenda iPhone huruka data ya JW Library kabisa. Habari njema: muundo wa nakala rudufu wa JW Library ni uleule kwenye Android, iPhone, iPad na Windows, kwa hiyo kuhama kati ya mifumo ni nakala rudufu tu, kuhamisha faili na kurejesha.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu kwenye simu ya Android", "JW Library → Funzo la Kibinafsi → menyu ya vitone vitatu → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu. Hifadhi faili la .jwlibrary."),
   ("Tuma faili kwenye iPhone au iPad", "Barua pepe, Google Drive, iCloud Drive — chochote kinachosogeza faili. Ikiwa iOS itabadilisha jina lake kuwa .zip njiani, libadilishe tena kuwa .jwlibrary."),
   ("Rejesha kwenye kifaa kipya", "Sakinisha JW Library, ujiandikishe, kisha Nakala Rudufu na Kurejesha → Rejesha kisha uchague faili. Madokezo, viangazio, alamisho, lebo na orodha za kucheza vyote hufika."),
  ],
  "sections": [
   ("Ikiwa iPhone tayari ina madokezo juu yake", "Kurejesha hubadilisha data ya kifaa. Kifaa kipya kinapokuwa tayari na madokezo yake, tengeneza nakala rudufu yake pia kisha uunganishe nakala zote mbili kuwa faili moja kwanza kwenye jwsync.org — muunganisho huunganisha maktaba zote mbili ndani ya kivinjari chako bila kupakia chochote — kisha urejeshe faili lililounganishwa. Hakuna kinachopotea kutoka upande wowote."),
   ("Hatua zilezile hufanya kazi pande zote", "iPhone kwenda Android, Android kwenda Android, kuongeza iPad kama kifaa cha pili cha funzo, au kuhamia programu ya Windows — faili la nakala rudufu ndilo lugha ya pamoja kati ya vyote."),
   ("Kwa nini muundo ni uleule kwenye mifumo yote miwili", "JW Library hutumia muundo uleule wa nakala rudufu kila mahali inapofanya kazi — Android, iOS, iPadOS na Windows. Faili la .jwlibrary ni ZIP lenye hifadhidata ya SQLite yenye majedwali yaleyale na muundo uleule bila kujali ni kifaa gani kilichoiandika. Hakuna hatua ya kubadilisha, hakuna densi ya kuhamisha-kisha-kuleta, wala hakuna chochote mahususi kwa mfumo ndani ya faili. Nakala rudufu ya Android hurejeshwa kwenye iPhone sawasawa na ile ya iPhone ingerejeshwa."),
   ("Sehemu pekee inayotofautiana kikweli", "Si faili — ni kulipata tu. Kwenye Android nakala rudufu huhifadhiwa kwenye folda unayochagua nayo inaweza kusogezwa kwa kidhibiti chochote cha mafaili. Kwenye iPhone hupitia karatasi ya kushiriki hadi Files, AirDrop, au chochote unachochagua. Kikwazo ambacho watu hukutana nacho wanapohama kati ya mifumo daima ni hatua hii ya kushughulikia, kamwe si upatanifu. Barua pepe, hifadhi ya wingu au AirDrop vyote hufanya kazi; kasha hufika likiwa zima au halifiki kabisa."),
   ("Rangi za viangazio, lebo na majibu ya funzo", "Vyote hunusurika. Rangi za viangazio huhifadhiwa kama namba — njano, kijani, buluu, waridi, chungwa na zambarau — nazo huonekana vilevile kwenye kila mfumo. Lebo na viunganisho kati ya lebo na madokezo huhamia, vivyo hivyo majibu yaliyoandikwa kwenye sehemu za maswali ya funzo. Unachokiona kwenye iPhone baada ya kurejesha ndicho ulichokuwa nacho kwenye kifaa cha Android."),
   ("Ikiwa iOS haitakuruhusu kuchagua faili", "Hifadhi faili kwenye programu ya Files kwanza, kisha ulichague kutoka hapo badala ya kutoka kwenye kiambatisho cha barua pepe au hakikisho la programu ya gumzo. Baadhi ya programu humpa iOS nakala ya muda ya hakikisho badala ya faili halisi, na JW Library haiwezi kufungua hiyo. Ikiwa faili lilifika kama kiambatisho, ligonge, uchague Hifadhi kwenye Files, kisha urejeshe kutoka Files."),
   ("Andaa iPhone kabla ya kurejesha", "Sakinisha JW Library kutoka App Store kisha uisasishe hadi toleo la sasa kabla ya kurejesha chochote. Nakala rudufu iliyoandikwa na toleo jipya zaidi la programu inaweza kutumia muundo wa hifadhidata ambao toleo la zamani haelewi, na urejeshaji utakataliwa tu. Kujiandikisha popote si lazima — data ya funzo la kibinafsi hukaa ndani ya faili unalorejesha, si kwenye akaunti."),
   ("Ikiwa tayari umeanza kujifunza kwenye iPhone", "Tengeneza nakala rudufu ya iPhone kwanza. Kurejesha faili la Android moja kwa moja juu yake kungebadilisha chochote ulichoandika tangu uhame. Kuunganisha nakala hizo mbili hutoa faili moja lenye zote mbili, ambalo kisha unalirejesha — historia ya Android na madokezo mapya ya iPhone huishia kwenye maktaba ileile."),
   ("Kuendelea kutumia simu zote mbili baadaye", "Baadhi ya watu huweka kifaa cha zamani cha Android kama kisomaji cha pili badala ya kukistaafisha. Hilo linawezekana, lakini vifaa hivyo viwili vitatengana mara tu unapoandika juu ya vyote viwili, kwa sababu hakuna usawazishaji kati yavyo. Ikiwa unakusudia kutumia vyote viwili, panga kuunganisha nakala zake rudufu mara kwa mara badala ya kudhani vitabaki vikilingana."),
   ("Baada ya kuhama", "Ipe iPhone muda wa kupakua upya machapisho unayotumia zaidi, kisha ukague machache yenye madokezo ili kuthibitisha kila kitu kimefika — madokezo, rangi za viangazio, alamisho na lebo. Weka faili la nakala rudufu la Android hata baada ya kuhama kukamilika: ni picha yenye tarehe ya maktaba yako, na kuiweka hakugharimu chochote."),
  ],
  "faq": [
   ("Je, ninahitaji kompyuta kufanya hivi?", "Hapana. Uhamiaji wote unaweza kufanywa kutoka simu hadi simu kwa barua pepe au hifadhi ya wingu."),
   ("Je, rangi zangu za viangazio zitanusurika uhamiaji?", "Ndiyo — viangazio huweka rangi zake, madokezo huweka lebo zake, na alamisho huweka mahali pake."),
   ("Je, ninahitaji kompyuta kwa hili?", "Hapana. AirDrop, barua pepe au programu yoyote ya hifadhi ya wingu husogeza faili moja kwa moja kati ya simu hizo mbili."),
   ("Je, hufanya kazi upande mwingine — iPhone kwenda Android?", "Ndiyo, vivyo hivyo. Hatua zilezile hufanya kazi pande zote, ikiwa ni pamoja na kwenda na kutoka programu ya Windows."),
   ("Je, iPhone itahitaji machapisho yaleyale kupakuliwa?", "Ndiyo, kwa kuwa maudhui ya machapisho si sehemu ya nakala rudufu. Madokezo hujiunganisha tena na kila chapisho mara linapopakuliwa."),
   ("Je, ninahitaji kuweka simu ya Android baadaye?", "Hapana, mara utakapothibitisha madokezo yapo kwenye iPhone. Kagua machapisho machache yenye madokezo kabla ya kufuta au kuuza kifaa cha zamani."),
   ("Je, uhamishaji hufanya kazi kwa majibu ya maswali ya funzo?", "Ndiyo. Majibu yaliyoandikwa ni sehemu ya data ya funzo la kibinafsi nayo huhamia pamoja na mengine yote."),
   ("Je, kuna hatari yoyote ya kupoteza madokezo wakati wa kuhama?", "Si ikiwa utaweka nakala rudufu ya Android. Urejeshaji huandika kwenye iPhone wala haubadilishi kamwe faili linalosomwa, kwa hiyo la awali hubaki zima kama kimbilio. Liweke hadi uthibitishe iPhone ina kila kitu, na ikiwezekana hata baadaye — ni picha yenye tarehe ya maktaba yako."),
   ("Itakuwaje ikiwa simu ya Android haitengenezi nakala rudufu?", "Angalia nafasi ya kuhifadhi kwanza, kwa kuwa programu inahitaji nafasi ya kuandika faili. Ikiwa programu yenyewe ndiyo inayoshindwa, kuisasisha au kuwasha upya kifaa kwa kawaida hurekebisha. Data yako hubaki zima wakati unatafuta suluhisho."),
  ],
 },

 "backup-jw-library": {
  "title": "Jinsi ya kutengeneza nakala rudufu ya JW Library kwa usahihi",
  "h1": "Jinsi ya kutengeneza nakala rudufu ya JW Library kwa usahihi",
  "description": "Rutuba ya nakala rudufu ya sekunde 30: ni nini hasa kilicho ndani ya faili la .jwlibrary, wapi pa kuliweka, na kwa nini kuwa na la sasa kunafaa hata wakati hakuna kilichoharibika.",
  "intro": [
   "Nakala rudufu huchukua kama nusu dakika, nayo inafaa kuifanya zoea — ingawa si hasa kwa sababu ambayo watu hutoa kwa kawaida. Nakala Rudufu na Kurejesha ya JW Library yenyewe tayari huhamisha maktaba kwenye kifaa kipya vizuri kabisa, kwa hiyo nakala rudufu si sana bima kama vile ni malighafi ya kila kitu kingine ambacho ungependa kufanya na funzo lako.",
   "Faili la .jwlibrary ndilo umbo pekee ambalo maktaba yako huchukua nje ya programu. Ndilo unalounganisha wakati vifaa viwili vyote vimetumika kujifunza, ndilo unalofungua ili kusoma, kuweka lebo upya au kupanga miaka ya madokezo, ndilo unalotafuta kwa maana wakati unakumbuka nusunusu ulichoandika, na ndilo unalochopoa seti ya madokezo kutoka wakati unapotaka kumtumia rafiki baadhi. Kuwa na la sasa ndiko kunakofanya lolote kati ya hayo liwezekane.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu", "Fungua JW Library → Funzo la Kibinafsi → menyu ya vitone vitatu → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu. Hutoa faili la .jwlibrary lenye kila dokezo, kiangazio, alamisho na lebo."),
   ("Liweke mahali fulani nje ya simu", "Jitumie kwa barua pepe, au ulihifadhi kwenye Google Drive, iCloud au OneDrive. Nakala rudufu inayokaa kwenye simu pekee hutoweka pamoja na simu."),
   ("Rudia kwa ratiba", "Kila mwezi ni chaguo zuri la msingi; kabla ya mabadiliko yoyote ya simu, kuiweka upya au kusasisha mfumo ni lazima. Weka nakala za zamani — mafaili ni madogo, na nakala rudufu ya zamani imewaokoa watu wengi."),
  ],
  "sections": [
   ("Kosa la kawaida: kutegemea nakala rudufu ya wingu ya simu yenyewe", "Nakala rudufu ya simu nzima (Google One, nakala rudufu ya kifaa ya iCloud) mara nyingi hurejesha nakala ya zamani ya data ya JW Library — au haihifadhi kabisa. Faili la .jwlibrary ndiyo nakala rudufu pekee unayoidhibiti kikamilifu na unayoweza kuibeba kati ya mifumo. Chukulia nakala rudufu ya simu kuwa bahati, si mpango."),
   ("Umebaki na nakala rudufu mbili tofauti?", "Hutokea: nakala moja kutoka simu, nyingine ya zamani kutoka kompyuta kibao, kila moja ikiwa na madokezo yake ya kipekee. Huhitaji kamwe kuchagua kati yazo — ziunganishe kuwa faili moja kamili kwenye jwsync.org, bila malipo na kwa faragha, ndani ya kivinjari."),
   ("Faili lina nini, na halina nini", "Nakala rudufu hubeba data yako ya funzo la kibinafsi: madokezo, viangazio na rangi zake, alamisho, lebo, na majibu uliyoandika kwenye sehemu za maswali ya funzo. Haibebi machapisho yenyewe — hakuna Biblia, magazeti, vitabu, video wala sauti. Ndiyo maana nakala rudufu ya miaka ya funzo kwa kawaida ni megabaiti chache tu, na ndiyo maana kurejesha kwenye kifaa kipya hukuacha ukipakua machapisho upya wakati kila dokezo ulilloandika tayari limerudi mahali pake."),
   ("Uweke nakala rudufu ngapi", "Weka zaidi ya moja. Hitilafu inayowagharimu watu madokezo yao ni nadra kuwa faili lililopotea — ni nakala rudufu nzuri iliyoandikwa juu na mbaya, au urejeshaji uliofanywa kwenye kifaa kisicho sahihi. Kwa kuwa mafaili ni madogo, hakuna sababu ya kufuta za zamani: ziweke zikiwa na tarehe kwenye folda ndani ya hifadhi ya wingu. Nakala rudufu ya miezi sita iliyopita si bure hata baada ya kuwa na mpya zaidi, kwa sababu chochote ulichofuta kwa bahati mbaya tangu wakati huo bado kipo ndani yake."),
   ("Wapi pa kuziweka", "Mahali popote ambapo si kifaa chenyewe pekee. Folda ndani ya Drive, iCloud, Dropbox au OneDrive hufunika hali inayohesabika zaidi — kifaa kupotea, kuibiwa, kuwekwa upya au kuharibika. Kujitumia faili kwa barua pepe pia hufanya kazi nako kuna faida ya ziada ya kuliwekea tarehe. Faili lina madokezo yako mwenyewe ya funzo, kwa hiyo lishughulikie kwa uangalifu uleule ungetumia kwa hati yoyote ya binafsi."),
   ("Kuthibitisha nakala rudufu kabla ya kuitegemea", "Nakala rudufu ambayo hujawahi kuifungua ni dhana, si wavu wa usalama. Unaweza kufungua faili la .jwlibrary kwenye kivinjari chako kisha uone hasa madokezo, viangazio na alamisho yaliyomo — ukaguzi wa sekunde thelathini unaogeuza dhana kuwa uhakika. Hili linahesabika zaidi hasa kabla ya jambo lisiloweza kutenduliwa: kuweka upya kiwandani, kuuza, kutengeneza, au kusasisha mfumo kwa kiwango kikubwa."),
   ("Nyakati zinazofaa kutengeneza nakala rudufu kabla yake", "Wakati wowote ambapo kifaa hubadilisha mmiliki au hali: kusasisha mfumo, kuweka upya kiwandani, kutengeneza au kubadilisha skrini, kuuza, au kumpa mtu mwingine kifaa. Ongeza kwa hayo mwisho wa chochote ambacho ungechukia kukirudia — kusanyiko, mkusanyiko, kipindi cha kujiandaa kwa hotuba. Nakala rudufu ni rahisi na za haraka, kwa hiyo zoea la manufaa ni kuziunganisha na matukio badala ya kalenda."),
   ("Nakala rudufu ya simu si nakala rudufu ya JW Library", "Google One, nakala rudufu ya kifaa ya iCloud au kifaa cha kuhamisha cha mtengenezaji hufanya kazi katika kiwango cha kifaa nazo hushughulikia data ya ndani ya programu kwa njia isiyo thabiti. Watu hugundua mara kwa mara kuwa urejeshaji kamili wa simu ulirudisha programu na mipangilio yao lakini si madokezo yao ya funzo, au ulirudisha toleo la wiki kadhaa zilizopita. Faili la .jwlibrary ndiyo nakala pekee ambayo unaidhibiti maudhui yake na unaweza kuyathibitisha, kwa hiyo chukulia nakala rudufu ya kiwango cha simu kuwa bahati badala ya mpango."),
   ("Kulifanya kuwa zoea linalodumu", "Rutuba inayodumu kikweli ni ile iliyoambatanishwa na kitu unachokifanya tayari: tengeneza nakala rudufu unapomaliza kujiandaa kwa juma, au siku ileile unayofanya kazi zako nyingine za kawaida. Hifadhi kwenye folda ileile kila mara ili mafaili yakusanyike mahali pamoja, kisha uache za zamani hapo. Folda ya nakala rudufu zenye tarehe zinazorudi nyuma miaka ndilo umbo imara zaidi ambalo hili linaweza kuchukua, nayo huchukua sekunde chache kwa wiki kuitunza."),
  ],
  "faq": [
   ("Faili la nakala rudufu lina ukubwa gani?", "Kwa kawaida megabaiti chache hata kwa maktaba kubwa sana — ndogo vya kutosha kuwa kiambatisho cha barua pepe."),
   ("Je, kutengeneza nakala rudufu hubadilisha chochote kwenye simu yangu?", "Hapana. Huandika faili tu; maktaba yako haiguswi."),
   ("Je, nakala rudufu inajumuisha machapisho niliyopakua?", "Hapana. Data ya funzo la kibinafsi pekee. Machapisho hupakuliwa upya kwenye kifaa kipya, na madokezo yako hujiunganisha nayo yenyewe."),
   ("Je, ninaweza kufungua nakala rudufu ili kuona kilichomo?", "Ndiyo. Unaweza kufungua faili la .jwlibrary kwenye kivinjari chako kisha uvinjari kila dokezo, kiangazio na alamisho lililomo, bila kusakinisha chochote na bila faili kuondoka kwenye kifaa chako."),
   ("Je, nakala rudufu huisha muda?", "Hapana. Faili la .jwlibrary hubaki linaweza kurejeshwa bila kikomo. Rejesha kwenye toleo la sasa la JW Library badala ya la zamani, kwa kuwa programu husoma miundo ya zamani ya nakala rudufu lakini si mipya."),
   ("Je, nitengeneze nakala rudufu kabla ya kila mkutano?", "Si lazima. Unganisha nakala rudufu na matukio yanayoweza kukugharimu data — masasisho, matengenezo, vifaa vipya — pamoja na mdundo wa kawaida unaolingana na kiasi cha funzo ambacho ungejali kukirudia."),
   ("Je, inafaa kuweka nakala rudufu za miaka iliyopita?", "Ndiyo. Ni ndogo, na chochote ulichofuta kwa bahati mbaya tangu wakati huo bado kipo ndani yake."),
  ],
 },

 "jw-library-restore-replaced-notes": {
  "title": "Kurejesha katika JW Library kumebadilisha madokezo yako? Jinsi ya kuyarudisha",
  "h1": "Kurejesha kumebadilisha madokezo yako? Hivi ndivyo unavyounganisha nakala zote mbili",
  "description": "Kurejesha katika JW Library ni ubadilishaji kamili, si muunganisho — madokezo yaliyoandikwa baada ya tarehe ya nakala rudufu huonekana yamepotea. Ikiwa bado una mafaili yote mawili ya nakala rudufu, hakuna kilichopotea. Hii hapa ni suluhisho.",
  "intro": [
   "Ni wakati mbaya: unarejesha nakala rudufu kwenye kifaa ambacho tayari kilikuwa na madokezo, na urejeshaji hubadilisha kila kitu — madokezo uliyoandika tangu nakala hiyo huonekana yamepotea. Hili hutokea kwa sababu Nakala Rudufu na Kurejesha ya JW Library ni ubadilishaji kamili, si muunganisho.",
   "Jambo la msingi: ikiwa kazi mpya zaidi bado ipo kwenye faili lolote la nakala rudufu, kwa kweli hakuna kilichopotea. Suluhisho ni kuunganisha nakala hizo mbili badala ya kuchagua kati yazo.",
  ],
  "steps": [
   ("Simama — usirejeshe tena", "Kila urejeshaji hubadilisha data ya sasa ya kifaa. Pumzika kabla ya kitu kingine chochote kutoweka."),
   ("Tengeneza nakala rudufu ya kifaa kilivyo sasa hivi", "Funzo la Kibinafsi → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu. Hii huhifadhi hali ya sasa, iwe na nini."),
   ("Tafuta nakala rudufu yenye madokezo yaliyokosekana", "Faili la .jwlibrary ulilorejesha kutoka, au la awali zaidi — angalia barua pepe yako, Drive, iCloud na folda ya vipakuliwa."),
   ("Unganisha mafaili yote mawili kwenye jwsync.org", "Pakia nakala rudufu zote mbili. JW Sync huunganisha madokezo, viangazio, alamisho na lebo zote kutoka zote mbili kuwa faili moja jipya — ndani ya kivinjari chako, hakuna kinachopakiwa. Matoleo yanayogongana ya dokezo lilelile huonyeshwa kando kwa kando ili wewe uchague."),
   ("Rejesha faili lililounganishwa", "Nakala Rudufu na Kurejesha → Rejesha kwa kutumia .jwlibrary lililounganishwa. Seti zote mbili za madokezo zimerudi kwenye kifaa."),
  ],
  "sections": [
   ("Itakuwaje ikiwa hakuna nakala rudufu ya madokezo mapya zaidi?", "Ikiwa nakala pekee ya madokezo mapya ilikuwa kwenye kifaa na urejeshaji tayari umeandika juu yake, JW Library yenyewe haitoi njia ya kutendua. Ndiyo maana hatua ya 2 hapo juu — kutengeneza nakala rudufu ya hali ya sasa kabla ya kufanya lolote — inahesabika sana wakati wowote data inapoonekana si sahihi. Kuanzia sasa, rutuba ya kuunganisha kwanza hufanya tatizo hili lisiwezekane kimuundo."),
  ],
  "faq": [
   ("Je, muunganisho utaongeza mara mbili madokezo yanayoshirikiwa na nakala zote mbili?", "Hapana — vipengele vinavyofanana hutambuliwa na kuhifadhiwa mara moja. Ni matoleo yaliyo tofauti kikweli ya dokezo lilelile tu ndiyo huwekewa alama ya kukaguliwa."),
   ("Je, hili linaweza kurekebisha nakala rudufu isiyorejeshwa kabisa?", "Hilo kwa kawaida ni uharibifu wa faili badala ya kuandikwa juu — ona mwongozo wa kurekebisha nakala rudufu iliyoharibika hapa chini."),
  ],
 },

 "fix-corrupted-jw-library-backup": {
  "title": "Rekebisha nakala rudufu ya JW Library iliyoharibika isiyorejeshwa",
  "h1": "Kurekebisha nakala rudufu ya JW Library iliyoharibika kwa Daktari wa Maktaba",
  "description": "JW Library inakataa kurejesha faili lako la .jwlibrary? Daktari wa Maktaba huchunguza nakala rudufu ndani ya kivinjari chako, hurekebisha matatizo ya kawaida, na hutoa nakala safi inayorejeshwa.",
  "intro": [
   "Nakala rudufu isiyorejeshwa si lazima iwe nakala rudufu iliyopoteza madokezo yako. Mafaili mengi ambayo watu huyaita yameharibika yako imara kimuundo nayo yamekataliwa kwa sababu inayoweza kurekebishwa, au yameharibika wakati wa kuhamishwa kwa njia ambayo nakala mpya huitatua. Inafaa kupitia sababu kabla ya kulitupa faili.",
   "Wakati mwingine JW Library hukataa faili la nakala rudufu — urejeshaji hushindwa, hutoa hitilafu, au faili halifunguki. Sababu za kawaida: upakuaji uliokatizwa, hifadhi ya wingu iliyoliharibu faili, kiendelezi kilichobadilika njiani, au kutokupatana kwa ndani kulikojirundika kwa miaka ya matumizi.",
   "JW Sync ina Daktari wa Maktaba, kikagua kinachochunguza faili la .jwlibrary na kurekebisha matatizo ya kawaida — ndani kabisa ya kivinjari chako, bila faili kuondoka kwenye kifaa chako kamwe.",
  ],
  "steps": [
   ("Fungua JW Sync kisha upakie faili lenye tatizo", "Nenda jwsync.org kisha upakie faili la .jwlibrary lisilorejeshwa. (Ikiwa faili lilifika likiwa limebadilishwa jina kuwa .zip, libadilishe tena kuwa .jwlibrary kwanza — hilo peke yake hurekebisha kesi nyingi.)"),
   ("Endesha uchunguzi wa Daktari wa Maktaba", "Daktari huchunguza muundo wa ndani wa nakala rudufu kisha huorodhesha anachokipata — kuanzia mambo yasiyo na madhara hadi uharibifu halisi — kwa lugha rahisi."),
   ("Tekeleza marekebisho", "Mgusa mmoja hurekebisha kinachoweza kurekebishwa. Daktari hahariri kamwe faili lako la awali; hutoa nakala iliyosafishwa, kwa hiyo la awali hubaki bila kuguswa kama kimbilio."),
   ("Pakua kisha urejeshe faili lililorekebishwa", "Rejesha .jwlibrary iliyosafishwa kupitia Nakala Rudufu na Kurejesha → Rejesha ndani ya JW Library."),
  ],
  "sections": [
   ("Daktari pia hufanya kazi wakati wa kila muunganisho", "Ukaguzi uleule hufanyika kiotomatiki ndani ya injini ya kuunganisha, kwa hiyo nakala rudufu iliyounganishwa daima hukabidhiwa ikiwa safi — hata wakati mojawapo ya mafaili yaliyoingizwa yalikuwa na matatizo ambayo hukuyajua kamwe."),
   ("Wakati faili haliwezi kurekebishwa", "Ikiwa faili lilikatwa vibaya kiasi kwamba data haiko ndani yake, hakuna kifaa kinachoweza kuibuni tena. Daktari atasema hivyo kwa uwazi badala ya kutoa faili la mashaka — na hiyo ndiyo ishara ya kwenda kutafuta nakala ya awali kwenye barua pepe, Drive au iCloud, jambo ambalo pia linaonyesha kwa nini kuweka nakala rudufu za zamani kunafaa."),
   ("Nini maana ya “imeharibika” kwa kawaida", "Kwa vitendo ni nadra kuwa data iliyoharibika. Sababu za kawaida ni faili lililokatwa wakati wa kuhamishwa — likikatizwa na upakiaji ulioshindwa au programu ya gumzo iliyolibana — au kasha lililo zima lakini lenye kutokupatana kwa ndani ambako programu hukataa. Kwa kuwa faili la .jwlibrary ni ZIP linalofunika hifadhidata ya SQLite, tabaka lolote kati ya hayo mawili linaweza kuwa tatizo, nayo yanahitaji marekebisho tofauti. Faili lililokatwa haliwezi kurekebishwa nalo lazima lipatikane upya; hifadhidata isiyopatana kwa kawaida inaweza."),
   ("Uchunguzi hukagua nini hasa", "Uchunguzi huthibitisha kuwa kasha hufunguka, kuwa userData.db ni hifadhidata ya SQLite inayosomeka inayopita ukaguzi wa uadilifu, kuwa muundo unalingana na kile JW Library inatarajia, na kuwa manifest inapatana na hifadhidata inayoieleza — ikiwa ni pamoja na hash ambayo programu hutumia kuthibitisha kuwa faili halijabadilishwa. Kutolingana kati ya manifest na hifadhidata ni mojawapo ya sababu za kawaida zaidi za nakala rudufu iliyo sawa kiufundi kukataliwa wakati wa kurejesha, nako kunarekebishwa kwa urahisi."),
   ("Safu zilizoachwa peke yake kwa kawaida hazina madhara", "Uchunguzi wa nakala rudufu halisi mara nyingi utaripoti safu zinazorejelea kitu ambacho hakipo tena — kwa mfano kiangazio kinachoelekeza mahali pa chapisho palipohamishwa. Nakala rudufu za JW Library zenyewe kwa kawaida huwa na mamia ya hizi nazo hurejeshwa bila malalamiko. Ni matokeo ya kawaida ya machapisho kusasishwa baada ya muda, si ushahidi wa uharibifu, na kuziondoa si lazima ili faili lifanye kazi."),
   ("Kuokoa madokezo kutoka faili lisilorejeshwa", "Hata wakati nakala rudufu haiwezi kurekebishwa vya kutosha ili JW Library ikubali, madokezo yaliyomo mara nyingi bado yanasomeka. Kufungua faili kwenye kivinjari chako hukuruhusu kuona na kunakili maandishi ya madokezo moja kwa moja, jambo linalogeuza faili lisilotumika kuwa nyenzo ya funzo iliyookolewa. Ikiwa una nakala rudufu ya pili, ya zamani, inayorejeshwa, maudhui yanayosomeka kutoka lile lililoharibika yanaweza kuletwa pamoja nayo badala ya kuandikwa upya."),
   ("Wakati urejeshaji unashindwa bila hitilafu iliyo wazi", "JW Library mara nyingi hukataa faili bila kueleza kwa nini. Sababu za mara kwa mara zaidi ni manifest ambayo hash yake hailingani tena na hifadhidata inayoieleza, faili lililokatwa wakati wa kuhamishwa, au nakala rudufu iliyoandikwa na toleo jipya zaidi la programu kuliko lile unalorejeshea. La kwanza linaweza kurekebishwa, la pili linahitaji faili kupatikana tena kutoka chanzo chake, na la tatu hutatuliwa kwa kusasisha programu kabla ya kurejesha."),
   ("Kuliepuka wakati ujao", "Uharibifu mwingi hutokea njiani. Sogeza nakala rudufu kama mafaili badala ya kupitia chochote kinachoweza kuzibana upya, na upendelee hifadhi ya wingu, AirDrop au kebo kuliko programu za gumzo. Baada ya kuhamisha, thibitisha kuwa ukubwa wa faili unalingana na wa awali — faili dogo kwa kiasi kinachoonekana kuliko ulilotuma lilikatwa, na hakuna marekebisho yatakayorudisha baiti ambazo hazikufika kamwe."),
   ("Ikiwa hakuna kinachofanya kazi", "Faili lisiloweza kurekebishwa bado linaweza kusomeka, na kulisoma mara nyingi kunatosha — maandishi ya madokezo yanaweza kuokolewa moja kwa moja hata wakati JW Library inakataa faili. Unganisha hilo na nakala rudufu yoyote ya zamani inayorejeshwa nawe kwa kawaida utaishia na sehemu kubwa ya maktaba yako ikiwa zima. Kabla ya kuhitimisha kuwa faili halitumiki, lifungue kisha uone kilichomo kihalisi."),
  ],
  "faq": [
   ("Je, data yangu hupakiwa kwa ajili ya uchunguzi?", "Hapana. Uchunguzi, marekebisho na uhamishaji vyote hufanyika ndani ya kivinjari."),
   ("Je, inaweza kuokoa madokezo yaliyofutwa ndani ya JW Library?", "Hapana — hurekebisha muundo wa faili. Madokezo yaliyofutwa ndani ya programu kabla nakala rudufu haijatengenezwa hayamo ndani ya faili ili kuokolewa."),
   ("Je, kurekebisha faili kutapoteza madokezo yoyote?", "Marekebisho hufanyika kwenye nakala nayo hushughulikia matatizo ya kimuundo badala ya maudhui. Faili lako la awali halibadilishwi kamwe, kwa hiyo linabaki linapatikana ukitaka kuanza upya."),
   ("Kwa nini nakala yangu rudufu iliharibika?", "Mara nyingi zaidi faili lilibadilishwa njiani — likitumwa kupitia programu iliyolibana au kulikata, au upakiaji ambao haukukamilika. Kuhamisha faili tena kutoka chanzo cha awali kwa kawaida hulitatua."),
   ("Je, uchunguzi unaweza kuokoa madokezo niliyofuta ndani ya JW Library?", "Hapana. Mara kinapofutwa ndani ya programu na nakala rudufu mpya kutengenezwa, dokezo limeondoka kwenye faili hilo. Nakala rudufu ya zamani iliyotengenezwa kabla ya kufutwa bado itakuwa nalo."),
   ("Je, ninaweza kujua kutokana na ukubwa wa faili kama limekatwa?", "Mara nyingi ndiyo. Lilinganishe na la awali ikiwa bado unalo; upungufu mkubwa unamaanisha uhamishaji haukukamilika."),
   ("Je, nakala rudufu inayofunguka kwenye kivinjari inahakikishiwa kurejeshwa?", "Haihakikishiwi, lakini ni ishara kubwa kuwa kasha na hifadhidata viko imara, jambo linaloondoa hitilafu za kawaida zaidi."),
  ],
 },

 "edit-jw-library-notes": {
  "title": "Ona na uhariri madokezo ya JW Library ndani ya kivinjari chako",
  "h1": "Ona, tafuta na uhariri madokezo yako ya JW Library — Kichunguzi cha Funzo",
  "description": "Fungua nakala rudufu yoyote ya .jwlibrary ndani ya kivinjari chako ili kuvinjari, kutafuta, kuhariri, kuweka lebo upya, kubadilisha rangi na kusafisha kwa wingi madokezo, viangazio na alamisho zako za JW Library. Hakuna kinachopakiwa.",
  "intro": [
   "JW Library imejengwa kwa ajili ya kuandika madokezo, si kudhibiti maelfu yake. Kichunguzi cha Funzo hufungua nakala rudufu yoyote ya .jwlibrary moja kwa moja ndani ya kivinjari chako na kuigeuza kuwa kidhibiti cha maktaba kinachoweza kutafutwa na kuhaririwa — madokezo, viangazio na alamisho mahali pamoja, bila chochote kupakiwa popote.",
  ],
  "steps": [
   ("Pakia nakala rudufu", "Tengeneza nakala rudufu katika JW Library (Funzo la Kibinafsi → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu), kisha ufungue jwsync.org na kupakia faili kwenye Kichunguzi cha Funzo."),
   ("Vinjari na utafute kila kitu", "Vichupo vitatu — Madokezo, Viangazio, Alamisho — vyenye utafutaji wa maandishi kamili pamoja na vichujio vya rangi, lebo na chapisho. Kichupo cha Majibu ya Funzo pia huonyesha majibu uliyojaza kutoka machapisho."),
   ("Hariri palepale", "Fungua dokezo lolote ili kuhariri kichwa na maudhui yake kwa umbizo tajiri (nene, italiki, mstari chini, orodha), kubadilisha rangi ya kiangazio chake, na kuongeza au kuondoa lebo. Alamisho na rangi za viangazio huhaririwa kwa njia ileile."),
   ("Safisha kwa wingi", "Chagua madokezo mengi kwa mpigo mmoja ili kuyawekea lebo upya, kubadilisha rangi au kuyafuta pamoja — kwa kutendua na kurudia kamili, kwa hiyo kosa dogo si fatali kamwe. Unaweza pia kuchopoa kipindi cha tarehe cha madokezo kwenye nakala rudufu mpya, au kunakili madokezo kama Markdown."),
   ("Hamisha maktaba yako iliyohaririwa", "Pakua .jwlibrary iliyohaririwa kisha uirejeshe katika JW Library. Mabadiliko yako sasa yapo kwenye kifaa."),
  ],
  "sections": [
   ("Kwa nini kuhariri ndani ya kivinjari badala ya programu?", "Ukubwa. Kubadilisha jina la lebo kwenye madokezo 300, kubadilisha rangi ya kila kiangazio cha njano ndani ya chapisho moja, au kufuta miaka ya alamisho ya zamani ni kazi ya dakika hapa na ya masaa ya kugonga ndani ya programu. Faili linalohamishwa ni nakala rudufu ya kawaida ambayo JW Library huirejesha kama nyingine yoyote."),
  ],
  "faq": [
   ("Je, kuhariri huligusa nakala yangu rudufu ya awali?", "Hapana — hariri hufanyika kwenye nakala iliyo ndani ya kivinjari nazo huhifadhiwa kwenye faili jipya linalohamishwa. La awali linabaki lilivyokuwa."),
   ("Je, kuna kikomo cha ukubwa wa maktaba?", "Maktaba kubwa sana hugawanywa kwenye kurasa ili kuvinjari kubaki haraka; utafutaji na vichujio hufanya kazi kwenye kila kitu."),
  ],
 },

 "search-jw-library-notes": {
  "title": "Tafuta madokezo ya JW Library kwa maana — Uliza Maktaba Yako",
  "h1": "Uliza Maktaba Yako: tafuta madokezo yako ya JW Library kwa maana",
  "description": "Utafutaji wa kimaana kwa madokezo yako ya JW Library: pata dokezo unalolikumbuka nusunusu kwa kulieleza, hata usipokumbuka maneno yake hasa. Ndani ya kifaa, hufanya kazi bila intaneti, kwa faragha.",
  "intro": [
   "Kila mwenye miaka ya madokezo anajua tatizo: unakumbuka uliandika kuhusu kuvumilia majaribu kwa shangwe, lakini dokezo halina neno “uvumilivu”, kwa hiyo utafutaji wa neno kuu haupati chochote. Uliza Maktaba Yako hutafuta kwa maana badala yake — eleza wazo, nayo huleta juu madokezo yaliyo karibu nalo zaidi, yawe yameandikwaje.",
   "Hufanya kazi yote ndani ya kifaa chako: kielelezo cha lugha hupakuliwa mara moja kwenye kivinjari kisha hufanya kazi bila intaneti baadaye, kwa kasi ya WebGPU pale inapopatikana. Madokezo yako hayatumwi popote kamwe.",
  ],
  "steps": [
   ("Pakia nakala rudufu kwenye Kichunguzi cha Funzo", "Kwenye jwsync.org, pakia faili lako la .jwlibrary kisha ufungue kichupo cha Uliza."),
   ("Acha kielelezo kijiandae mara moja", "Katika matumizi ya kwanza kielelezo cha ndani ya kifaa hupakuliwa na kufanya faharasa ya madokezo yako. Hili hutokea mara moja; baadaye hufanya kazi papo hapo, hata bila intaneti."),
   ("Uliza kwa maneno yako mwenyewe", "Andika unachokumbuka — “lile dokezo kuhusu kuwa mvumilivu na wapya kazini”, “kitia-moyo kwa mapainia waliovunjika moyo” — nayo madokezo yaliyo karibu zaidi huonekana, yakipangwa kwa maana."),
  ],
  "sections": [
   ("Jinsi inavyotofautiana na utafutaji wa kawaida", "Utafutaji wa neno kuu hulinganisha herufi; utafutaji wa kimaana hulinganisha mawazo. Swali kuhusu “wasiwasi” pia hupata madokezo yaliyoandikwa kwa kutumia “hangaiko”, “mahangaiko ya maisha” au andiko lililotajwa juu ya mada hiyo. Aina zote mbili za utafutaji zipo ndani ya Kichunguzi cha Funzo — hukamilishana."),
   ("Faragha kwa muundo", "Hii si huduma ya AI ya wingu. Kielelezo hufanya kazi ndani ya kichupo chako cha kivinjari, faharasa hukaa kwenye kifaa chako, na kufunga kichupo ndio mwisho wake. Hakuna chochote kuhusu madokezo yako kinachoondoka kwenye mashine yako kamwe."),
  ],
  "faq": [
   ("Je, inahitaji kifaa chenye nguvu?", "Simu au kompyuta mpakato ya kisasa huimudu vizuri; kwenye vifaa vyenye WebGPU ndiko kwa kasi zaidi. Kuna chaguo la ukubwa wa vielelezo linalolingana na maunzi yako."),
   ("Je, hufanya kazi katika lugha yangu?", "Ndiyo — utafutaji hufanya kazi katika lugha ambazo madokezo yako yameandikwa, na kiolesura kimetafsiriwa katika kila lugha ambayo JW Sync inaunga mkono."),
  ],
 },

 "jw-library-study-stats": {
  "title": "Ona takwimu zako za funzo la JW Library: mifululizo, ramani za shughuli na tuzo",
  "h1": "Takwimu zako za funzo la JW Library: mifululizo, ramani za shughuli, ufikiaji na tuzo",
  "description": "Geuza nakala rudufu ya JW Library kuwa uchanganuzi wa faragha wa funzo — jumla, ramani ya shughuli, mifululizo, ufikiaji wa Biblia katika vitabu 66, wasifu wa tabia ya funzo na tuzo takriban 200.",
  "intro": [
   "Faili lako la nakala rudufu hurekodi kimyakimya miaka ya historia ya funzo — wakati unapoandika madokezo, unachokiangazia, vitabu ulivyovipitia. Ukurasa wa Takwimu za Funzo husoma nakala rudufu ya .jwlibrary na kugeuza historia hiyo kuwa dashibodi ya faragha, iliyokokotolewa ndani kabisa ya kivinjari chako.",
  ],
  "steps": [
   ("Tengeneza nakala rudufu", "Katika JW Library: Funzo la Kibinafsi → Nakala Rudufu na Kurejesha → Tengeneza nakala rudufu."),
   ("Fungua ukurasa wa Takwimu za Funzo", "Nenda jwsync.org/highlights.html kisha upakie faili."),
   ("Chunguza hadithi ya funzo lako", "Jumla kuu, mwonekano wa Mwaka wa Utumishi na wa Nyakati Zote, ukuaji mwaka baada ya mwaka — kisha sehemu za kufurahisha zilizo hapa chini."),
  ],
  "sections": [
   ("Utakachoona", "Ramani ya shughuli yenye mfululizo wako mrefu zaidi na wa sasa; mdundo wa juma, saa na miezi yenye shughuli nyingi zaidi; ufikiaji wa Biblia katika vitabu vyote 66 pamoja na mgawanyo wa Maandiko ya Kiebrania na ya Kigiriki; gurudumu la rangi za viangazio, histogramu ya kina cha madokezo na wingu la maneno; saa ya funzo ya saa 24 na rada ya misimu."),
   ("Wasifu, safari na tuzo", "Wasifu wa Funzo wenye sifa sita (Uthabiti, Bidii, Kina, Upana, Tafakari, Uimara) pamoja na tabia ya “Alama ya Funzo”; Safari ya Funzo ya ngazi 60 katika madaraja 12 yenye majina; na tuzo takriban 200 kuanzia za Kawaida hadi za Kisasa, ikiwa ni pamoja na medali zinazozingatia maudhui. Kadi ya Kushirikiwa hufupisha mwaka wako bila kufichua hata dokezo moja."),
   ("Sababu ya kila siku ya kurudi", "Paneli ya Kumbusho huonyesha madokezo uliyoandika siku kama ya leo katika miaka iliyopita nayo hujenga marudio ya taratibu yaliyotawanywa kwa muda — kidogo, mara kwa mara, ndiyo njia ya funzo kubaki akilini."),
  ],
  "faq": [
   ("Je, chochote kati ya haya hupakiwa?", "Hapana. Nakala rudufu huchanganuliwa ndani ya kivinjari chako; takwimu haziondoki kwenye kifaa chako kamwe."),
   ("Je, takwimu hujisasisha zenyewe?", "Huakisi nakala rudufu unayoipakia — tengeneza nakala rudufu mpya ili kuona takwimu mpya."),
  ],
 },

 "share-jw-library-notes": {
  "title": "Jinsi ya kushiriki madokezo ya JW Library na rafiki",
  "h1": "Jinsi ya kushiriki madokezo ya JW Library na rafiki — bila seva",
  "description": "Mtumie rafiki madokezo uliyochagua ya JW Library (pamoja na viangazio vyake) kama faili dogo — hakuna seva, hakuna akaunti. Mpokeaji huyaunganisha bila kuandika juu ya madokezo yake mwenyewe.",
  "intro": [
   "JW Library haina njia ya kumpa mtu mwingine nakala ya madokezo mahususi. Kutuma nakala yako rudufu nzima kungefanya kazi — lakini hukabidhi kila kitu, na kuirejesha kungefuta maktaba ya mpokeaji mwenyewe. Kushiriki madokezo kwa JW Sync hutatua matatizo yote mawili: chagua hasa madokezo ya kushiriki, naye mpokeaji huyaongeza bila kupoteza chochote.",
  ],
  "steps": [
   ("Chagua madokezo ya kushiriki", "Kwenye ukurasa wa Kushiriki katika jwsync.org/share.html, pakia nakala yako rudufu kisha uchague madokezo — machache kutoka hotuba moja, au kila kitu chini ya lebo kwa mbofyo mmoja kwa kutumia kichujio cha lebo cha kikagua. Viangazio vilivyoambatishwa na madokezo hayo husafiri pamoja."),
   ("Tuma faili la kushiriki", "JW Sync hutoa faili dogo lenye madokezo uliyochagua tu. Litume kwa njia yoyote unayopenda — programu ya ujumbe, barua pepe, AirDrop. Hakuna seva wala akaunti; faili ndilo badiliano lote."),
   ("Mpokeaji hulliunganisha", "Rafiki yako hufungua ukurasa uleule, hupakia faili la kushiriki pamoja na nakala yake rudufu, kisha hupata nakala rudufu mpya yenye madokezo yako yameongezwa. Madokezo yake mwenyewe hayaandikwi juu kamwe — ikiwa dokezo lililoshirikiwa linagongana na lake, yeye huchagua jinsi linavyoongezwa — nayo madokezo yaliyoletwa hufika yakiwa na lebo, kwa hiyo ni rahisi kuyapata, kuyakagua au kuyaondoa baadaye."),
  ],
  "sections": [
   ("Matumizi mazuri", "Kupitisha utafiti kwa mwenzako wa funzo, kushiriki madokezo ya mkutano na mtu aliyekuwa hayupo, kumpa mhubiri mpya seti ya kuanzia ya madokezo juu ya chapisho, au kuhamisha madokezo ya mradi mahususi kwenda kwa mtu wa familia — yote bila kufichua sehemu nyingine ya maktaba ya upande wowote."),
  ],
  "faq": [
   ("Je, mpokeaji anahitaji kusakinisha JW Sync?", "Hakuna kinachosakinishwa upande wowote — ni ukurasa wa wavuti. Mpokeaji anahitaji tu faili la kushiriki na nakala yake rudufu."),
   ("Je, ninaweza kutengua kushiriki au kufanya faili lililoshirikiwa liishe muda?", "Faili ni faili la kawaida ulilotuma — hakuna nakala kwenye seva ya kuisha muda. Shiriki tu kile ambacho ungeshiriki katika ujumbe wowote."),
  ],
 },

 "bible-reading-plan": {
  "title": "Ratiba ya kila siku ya kusoma Biblia pamoja na madokezo yako mwenyewe kando yake",
  "h1": "Mwandani wa Kusoma: ratiba ya kusoma Biblia pamoja na madokezo yako mwenyewe kando yake",
  "description": "Ratiba ya faragha ya kila siku ya kusoma Biblia inayoonyesha madokezo na viangazio ulivyotengeneza kwenye sura za leo. Chagua kasi yako, dumisha mfululizo, uone gridi ya vitabu 66 ikijaa.",
  "intro": [
   "Programu nyingi hutoa ratiba ya kusoma Biblia. Mwandani wa Kusoma hufanya jambo ambalo hakuna mojawapo inayoweza: kwa sababu husoma nakala yako rudufu ya .jwlibrary, usomaji wa leo hufika pamoja na madokezo na viangazio ulivyotengeneza wewe mwenyewe kwenye sura hizohizo — “uliangazia mistari minne katika Zaburi 37 miaka miwili iliyopita.” Kusoma kupitia kioo cha historia yako mwenyewe ya funzo, ndani kabisa ya kifaa chako.",
  ],
  "steps": [
   ("Chagua mpangilio na kasi", "Soma kwa mpangilio wa Biblia au kwa mpangilio wa takribani wa matukio; maliza katika miezi 3, miezi 6, mwaka 1, miaka 2, au weka kasi yako mwenyewe ya sura kwa siku — pamoja na hakikisho hai la “ungemaliza karibu na…”."),
   ("Soma fungu la leo", "Kila sura iko mgusa mmoja tu, ikifunguka moja kwa moja ndani ya JW Library au WACHTTOWER ONLINE LIBRARY katika lugha yako. Weka alama kwenye sura unapoendelea."),
   ("Leta madokezo yako pamoja (si lazima)", "Pakia nakala rudufu kwenye kifaa chochote cha JW Sync na madokezo yako mwenyewe pamoja na idadi ya viangazio huonekana mara moja chini ya sura za leo."),
   ("Ona maendeleo yakijengeka", "Gridi ya vitabu 66 hujaa unaposoma, pamoja na upau wa sura zilizosomwa, utabiri wa kasi, na hatua muhimu za kumaliza kila kitabu, Maandiko ya Kiebrania na Kiaramu, Maandiko ya Kigiriki — na Biblia nzima."),
  ],
  "sections": [
   ("Mifululizo bila hatia", "Kumaliza siku hukuza mfululizo wako; kukosa siku husogeza tu tarehe inayotabiriwa ya kumaliza. Hakuna rundo la madeni — ratiba hujipinda kulingana na maisha yako badala ya kukukemea."),
  ],
  "faq": [
   ("Je, ninahitaji kupakia nakala rudufu ili kuitumia?", "Hapana — ratiba, mifululizo na maendeleo hufanya kazi vyenyewe. Nakala rudufu huongeza tu madokezo yako binafsi kwenye usomaji wa kila siku."),
   ("Je, maendeleo yangu ya kusoma ni ya faragha?", "Ndiyo. Maendeleo hukaa ndani ya kivinjari chako kwenye kifaa chako — hakuna akaunti wala kinachopakiwa."),
  ],
 },
}
